### PR TITLE
workflow: pr: enable tests in all archs

### PR DESCRIPTION
**Pull request by geyslan**
### 1. Explain what the PR does
commit 6d50e229d2964b512df2b9ff61a6c6485d7c0715

    workflow: pr: enable tests in all archs
    
    trc-105 and trc-1022
    
    addendum: TRC-1022 disabled in ARM64_TESTS since it doesn't work on
    Focal 4.19 and 5.4

### 3. Other comments

This requires prior merging of
- https://github.com/aquasecurity/tracee-tester/pull/4

### CODE REVIEW

**Comment by geyslan** [comment]
@rafaeldtinoco, please take a look https://github.com/aquasecurity/tracee/pull/2863/checks

**Comment by rafaeldtinoco** [comment]
https://github.com/aquasecurity/tracee-tester/pull/3 was merged and reverted as it broken AMD64 TRC-105 tests (like said in that PR comments).

I'm marking this as draft for now until tracee-tester is fully fixed. Also adding to the milestone v0.13.0 as this is chore and has no issue associated to it.

**Comment by yanivagman** [comment]
> Well, this is curious, TRC-1022 is failing only in two arm64 kernels (focal 4.19 and 5.4).

These are the older kernels, so there may be some symbol missing in these kernels for ARM64 used by the magic_write event (which is used by the TRC-1022 signature)

**Comment by geyslan** [comment]
Just for clarification: 

```shell
❯ comm -23 focal513-arm64-config-sorted focal540-122-arm64-config-sorted | grep 'DEBUG' | grep -v '#'
CONFIG_ARCH_HAS_DEBUG_VM_PGTABLE=y
CONFIG_ARCH_HAS_DEBUG_WX=y
CONFIG_ATH11K_DEBUGFS=y
CONFIG_DEBUG_FS_ALLOW_ALL=y
CONFIG_DEBUG_INFO_BTF_MODULES=y
CONFIG_DYNAMIC_DEBUG_CORE=y
CONFIG_RTW89_DEBUGFS=y
CONFIG_RTW89_DEBUGMSG=y
CONFIG_RTW89_DEBUG=y

❯ comm -23 focal513-arm64-config-sorted focal540-122-arm64-config-sorted | grep 'SYMBOL' | grep -v '#'
CONFIG_SYMBOLIC_ERRNAME=y

# kallsyms
❯ grep -i trace kallsyms-only-in-focal513-not-in-focal54-arm64 | grep -v '#' | wc -l                           
2783
```

I'll remove TRC-1022 tests from those two kernel, anyway.

**Comment by rafaeldtinoco** [comment]
@geyslan The event `magic_write` is broken in v5.4 ARM64:

### ARM64

```
{"timestamp":1679491687512897112,"threadStartTime":1679491687511705389,"processorId":0,"processId":11,"cgroupId":4294967408,"threadId":11,"parentProcessId":1,"hostProcessId":10186,"hostThreadId":10186,"hostParentProcessId":9952,"userId":0,"mountNamespace":4026532446,"pidNamespace":4026532449,"processName":"cp","hostName":"d3a5151033b6","containerId":"d3a5151033b613a047ca86cfd3021efbc21efe7c57ccb0ce4fd19b8e3cda8ffe","containerImage":"","containerName":"","podName":"","podNamespace":"","podUID":"","podSandbox":false,"eventId":"725","eventName":"magic_write","matchedPolicies":1,"argsNum":4,"returnValue":125736,"syscall":"","stackAddresses":null,"contextFlags":{"containerStarted":true,"isCompat":false},"args":[{"name":"pathname","type":"const char*","value":"/ls"},{"name":"bytes","type":"bytes","value":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="},{"name":"dev","type":"dev_t","value":54},{"name":"inode","type":"unsigned long","value":1314215}]}
```

### X64

```
{"timestamp":1679491729273348099,"threadStartTime":1679491729272198727,"processorId":4,"processId":9,"cgroupId":58,"threadId":9,"parentProcessId":1,"hostProcessId":41778,"hostThreadId":41778,"hostParentProcessId":41702,"userId":0,"mountNamespace":4026532374,"pidNamespace":4026532377,"processName":"cp","hostName":"da936d30d9aa","containerId":"da936d30d9aaa27ec9336c5529df0135f3e554d23eebc9382d9ec07211d5b3bc","containerImage":"","containerName":"","podName":"","podNamespace":"","podUID":"","podSandbox":false,"eventId":"725","eventName":"magic_write","matchedPolicies":1,"argsNum":4,"returnValue":131072,"syscall":"write","stackAddresses":null,"contextFlags":{"containerStarted":true,"isCompat":false},"args":[{"name":"pathname","type":"const char*","value":"/ls"},{"name":"bytes","type":"bytes","value":"f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAAsGoAAAAAAAA="},{"name":"dev","type":"dev_t","value":100},{"name":"inode","type":"unsigned long","value":1191737}]}
```

**Comment by rafaeldtinoco** [comment]
I have opened a bug for this issue: https://github.com/aquasecurity/tracee/issues/2904

And I'll add a comment there saying the signature "1022" should be enabled in ARM64 whenever that issue is fixed.

**Review by rafaeldtinoco — APPROVED** [review]
With the discovery of WHY the TRC-1022 tests were failing, I have opened a bug to address the issue. NOW this can be accepted and merged.

**Pull request merged**
