### PR TITLE
fix(processors): change args values by name

### PR DESCRIPTION
**Pull request by AlonZivony**
### 1. Explain what the PR does

Change all places that change args values in processors to find arguments by their names instead of index.
This way the order of the arguments received from the kernel shall not cause bugs.

### CODE REVIEW

**Comment by geyslan** [comment]
@AlonZivony even not reproducing the issue I was doing changes similar to yours. That's great.

Could you please just add another fix to it? Please, see procTreeForkRemoveArgs(). It's not updating ArgNum.

**Comment by josedonizetti** [comment]
@AlonZivony Thanks! Not doing it through a set is a current problem of migrating to the new event structure, kind of doing something similar there! :D

**Comment by geyslan** [comment]
> @AlonZivony even not reproducing the issue I was doing changes similar to yours. That's great.
> 
> Could you just add another fix to it? Please, see procTreeForkRemoveArgs(). It's not updating ArgNum.

Already done that fix in https://github.com/aquasecurity/tracee/pull/3839

**Review by josedonizetti — APPROVED** [review]

**Comment by yanivagman** [comment]
LGTM

**Comment by geyslan** [comment]
> LGTM

Please don't merge before getting this into https://github.com/AlonZivony/tracee/pull/4

@AlonZivony

**Comment by AlonZivony** [comment]
@geyslan I added it as part of this PR.
This is why I have put you as a co-author for the commit

**Comment by NDStrahilevitz** [comment]
@AlonZivony Can this be merged for the release?

**Pull request merged**
