### PR TITLE
filters: integrate new filters protocol

### PR DESCRIPTION
**Pull request by NDStrahilevitz**
## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [ ] Git log contains summary of the change.
- [ ] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

This PR currently adds a new filters package, intended to replace the existing filters in `pkg/tracee/filters.go`.
These filters should work exactly the same as the existing ones with the added ability of being able to be changed during runtime.

Additionally, it makes use of the new `protocol.Filter` to create a later common interface between parsing the cli into the main Filter struct, and a gRPC service we will add later to receive mediated filters from tracee-rules.
It refactors filter parsing from the CLI - switching to parse into `[]protocol.Filter` which is down the line parsed into a `tracee.Filter`.

While this tries to maintain a high degree of similarity to the previous filtering logic, this PR probably breaks previous behavior.

Fixes: #1727 

## Type of change

- [x] Code refactor (code improvement and/or code removal)
- [x] New feature (non-breaking change adding functionality).
- [x] Breaking change (cause existing functionality not to work as expected) (possibly?).

## How Has This Been Tested?

New unit tests were added to the new filters package.
Tests were moved and changed according to the new flow of filter info.

Reproduce the test by running:

`make test-unit`

## Final Checklist:

- [x] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented all functions/methods created explaining what they do.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix, or feature, is effective.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Comment by NDStrahilevitz** [comment]
Tests are failing because I am still considering how to rework the flag tests in tracee-ebpf and if they should exist at all (as theoretically the parser tests should cover them).

**Comment by yanivagman** [comment]
This PR is too big to be in one commit. Please split.

**Comment by NDStrahilevitz** [comment]
> This PR is too big to be in one commit. Please split.

You mean too big for one PR or too big for one commit?

**Comment by yanivagman** [comment]
> > This PR is too big to be in one commit. Please split.
> 
> You mean too big for one PR or too big for one commit?

For one commit

**Comment by yanivagman** [comment]
Making small and self contained commits makes the review much easier

**Comment by NDStrahilevitz** [comment]
> Making small and self contained commits makes the review much easier

I've split it into 2 commits, one introducing only the package code, and the other one integrating it into tracee-ebpf.

**Review by yanivagman — CHANGES_REQUESTED** [review]
I must say that the refactor commit is still too big.
I left a few comments, but I didn't fully review this PR because it is just too big and hard to review.
Please try to break the refactor commit into smaller commits, or even better, do smaller PRs for self contained changes, so we can move faster with this review.

**Comment by NDStrahilevitz** [comment]
Opening #2009 instead of this

**Pull request closed without merging**
