### PR TITLE
[MAINT] Bump libbpfgo again

### PR DESCRIPTION
**Pull request by rafaeldtinoco**
## Initial Checklist

- [ ] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

Let's try to bump to libbpfgo v0.4.0 and libbpf 1.0.0 one more time, earlier in the milestone this time. Note that I'm bumping to a specific commit of libbpfgo because we needed the CGO fixes made by the following commit of that project:

commit 14c6bc9 (HEAD -> main, origin/main, origin/HEAD)
Author: rotscale <grantseltzer@gmail.com>
Date:   Fri Sep 16 13:44:11 2022

    Move logic into C code via cgo

## How Has This Been Tested?

Tests being included in this PR:

Quick change in test recently added by @AlonZivony at commit:

commit 03f9221d
Author: Rafael David Tinoco <rafaeldtinoco@gmail.com>
Date:   Tue Sep 20 15:35:47 2022

    parse_args: fix {get,set}sockopt new parse option

Because of needed changes (newer API).

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created, explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
BTW... I ** THINK ** that integration tests fail when we try to bump "go mod tidy", so I did not do (might require some more tests/effort).

**Review by josedonizetti — APPROVED** [review]

**Comment by NDStrahilevitz** [comment]
Still failing on my ubuntu 22.04 machine like in the previous bump.
image

**Comment by josedonizetti** [comment]
@grantseltzer @geyslan Funny, when I reviewed this PR for Rafael, I did `make clean`, `git submodule update`, `go clean -modcache` and `make` and no error happened when I run `./dist/tracee-ebpf`. But I have tracee cloned in two different places, on the other cloned repo, doing the same things, and it never works, I see the error everytime in one folder, and never on the other. 

Let me know how I can help.

**Comment by NDStrahilevitz** [comment]
@geyslan @josedonizetti It was the mod cache, got help from @rafaeldtinoco after making another small project with latest libbpfgo.

**Comment by geyslan** [comment]
> But I have tracee cloned in two different places, on the other cloned folder, doing the same things, and it never works, I see the error everytime in one folder, and never on the other.

@josedonizetti Odd. Let's try a dive? Stack trace?

**Pull request merged**
