### PR TITLE
refactor: simplify output flags

### PR DESCRIPTION
**Pull request by josedonizetti**
### 1. Explain what the PR does

Simplify output logic in order to add multiple printer support in a follow-up pr. Also increase test coverage. 

### 2. Explain how to test it

compile `tracee`, and test --output

### 3. Other comments

This is a refactor in order to add multiple printers supported, required by the new binary.
https://github.com/aquasecurity/tracee/issues/2355

### CODE REVIEW

**Review by NDStrahilevitz — APPROVED** [review]
LGTM

**Comment by rafaeldtinoco** [comment]
This is for v0.11.1 and not for v0.12.0, right ? Please hold!

> @yanivagman an example why I need the milestone on PRs. Now if someone flags milestone/next label, I can't tell if its for v0.11.1 or v0.12.0 (just one example to show you why I preferred that way).

**Comment by josedonizetti** [comment]
@rafaeldtinoco Yes! It can hold for 0.12.0

**Review by geyslan — APPROVED** [review]
LGTM

**Pull request merged**
