### PR TITLE
tracee-ebpf: update external module

### PR DESCRIPTION
**Pull request by yanivagman**
PR #837 changed the external module files.
Update go.mod to point to the updated module.

### CODE REVIEW

**Review by itaysk — COMMENTED** [review]
also need to update tracee-rules

**Comment by itaysk** [comment]
@danielpacak I think we can also remove this? https://github.com/aquasecurity/tracee/blob/443955e3c087f8e7652420c9d947cf5fe3c51756/tracee-ebpf/external/external.go#L64:L67

**Comment by danielpacak** [comment]
> @danielpacak I think we can also remove this? https://github.com/aquasecurity/tracee/blob/443955e3c087f8e7652420c9d947cf5fe3c51756/tracee-ebpf/external/external.go#L64:L67

You are right Itay. Now we can just

`"timestamp": json.Number(strconv.Itoa(e.Timestamp))`

instead of

`"timestamp": json.Marshal(e.Timestamp)`

**Comment by yanivagman** [comment]
@danielpacak I can do this update here, but then again we will need to update the external module in a different PR.
So maybe do this change now and I'll rebase?

**Comment by danielpacak** [comment]
> @danielpacak I can do this update here, but then again we will need to update the external module in a different PR (go.mod will have to be changed in tracee-ebpf and tracee-rules as we change the external.go of the external module).
> So maybe do this change now and I'll rebase?

Yeah, let's do it in scope of this PR. Someone will have to that anyway

**Comment by yanivagman** [comment]
Ok, I think I'll open a different PR for this change (It will be funny to update external module twice)

**Comment by yanivagman** [comment]
Opened #842.
Tests will not pass there, but let's merge and I'll rebase this PR on it, which will also fix the build

**Comment by yanivagman** [comment]
Ok, so surprisingly after rebasing and doing "go get" nothing changed in go.mod (not sure why), so we can merge this one now

**Comment by danielpacak** [comment]
> Ok, so surprisingly after rebasing and doing "go get" nothing changed in go.mod (not sure why), so we can merge this one now

Shouldn't we point to the latest commit in bot tracee-ebf/go.mod and tracee-rules/go.mod ?

```
-       github.com/aquasecurity/tracee/tracee-ebpf/external v0.0.0-20210727054623-f17c1d161b64
+       github.com/aquasecurity/tracee/tracee-ebpf/external v0.0.0-20210727091827-bbe411a2a167
```

I also realised that external_test.go if failing due to change in Timestamp type from float64 to int.

**Comment by yanivagman** [comment]
> Shouldn't we point to the latest commit in both tracee-ebf/go.mod and tracee-rules/go.mod ?

What do you mean? In this PR they both point to f17c1d161b64

**Comment by yanivagman** [comment]
> I also realised that external_test.go if failing due to change in Timestamp type from float64 to int.

We should add this test to the pipeline

**Comment by danielpacak** [comment]
> > Shouldn't we point to the latest commit in both tracee-ebf/go.mod and tracee-rules/go.mod ?
> 
> What do you mean? In this PR they both point to [f17c1d1](https://github.com/aquasecurity/tracee/commit/f17c1d161b640966f77e7d9ee164ee535e141987)

Yes, but the latest commit on the main branch is bbe411a not f17c1d1. Unless I took it all wrong 🤯

**Comment by yanivagman** [comment]
> Yes, but the latest commit on the main branch is bbe411a not f17c1d1. Unless I took it all wrong exploding_head

You are right. For some reason, it didn't pull the latest changes for me when I did `go get`. Now everything seems to be aligned.

**Review by danielpacak — APPROVED** [review]
LGMT!

**Pull request merged**
