### PR TITLE
ebpf: add prog_override_return arg to bpf_attach

### PR DESCRIPTION
**Pull request by roikol**
add argument to the bpf_attach event indicating whether the bpf_override_return helper function is used.
this is to be used later on in the signatures phase.

## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

```
Author: RoiKol <roi.kol@aquasec.com>
Date:   Tue Jan 10 15:29:23 2023 +0200

    ebpf: add prog_override_return arg to bpf_attach
    
    add argument to the bpf_attach event indicating whether the
    bpf_override_return helper function is used
```

Fixes: #2558

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [x] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## How Has This Been Tested?

locally using my own sample of BPF program that uses the `bpf_override_return` helper.

Reproduce the test by running:

- command 01: `./dist/tracee-ebpf -t e=bpf_attach`

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [x] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented all functions/methods created explaining what they do.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix, or feature, is effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Review by rafaeldtinoco — APPROVED** [review]
LGTM. Retrying tests and will run e2e before merging as we're close to releasing.

**Review by rafaeldtinoco — CHANGES_REQUESTED** [review]
breaking E2E

**Comment by roikol** [comment]
> breaking E2E

now passing

**Review by rafaeldtinoco — CHANGES_REQUESTED** [review]
@roikol, There was a huge change in `tracee.bpf.c` where most of the code differing during the rebase was placed in other header files. If you rebase your code to it I'm able to merge this one soon. Tks!

**Comment by roikol** [comment]
> @roikol, There was a huge change in `tracee.bpf.c` where most of the code differing during the rebase was placed in other header files. If you rebase your code to it I'm able to merge this one soon. Tks!

thanks @rafaeldtinoco !
now rebased and ready

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Pull request merged**
