### PR TITLE
Add file modification event

### PR DESCRIPTION
**Pull request by roikol**
this PR is the same as #2608 , but rebased

### 1. Explain what the PR does

```
Author: RoiKol <roi.kol@aquasec.com>
Date:   Tue Jan 24 23:03:29 2023 +0200

    tests: add e2e file_modification test

commit 81030a27856d44d73cf8efa2482eb16e0338b8b3
Author: RoiKol <roi.kol@aquasec.com>
Date:   Tue Jan 24 13:46:46 2023 +0200

    events: add file_modification event
```

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
Added a comment in the issue:

https://github.com/aquasecurity/tracee/issues/2728#issuecomment-1449160227

regarding next steps. We're accepting this PR, even with those reservations, in order to have the feature included in this milestone. There are a few things still to be covered though (and that issue should be open after this is merged).

**Comment by rafaeldtinoco** [comment]
@roikol thanks for the discussion and for bringing this PR again to the milestone.

**Review by rafaeldtinoco — APPROVED** [review]
This PR was already approved before (it is brought back because the feature needs to enter this milestone). I'm doing my +1 here and left some things to be covered by next milestone(s). Cheers!

**Comment by roikol** [comment]
thanks @rafaeldtinoco !!

**Pull request merged**
