### PR TITLE
libbpf bump

### PR DESCRIPTION
**Pull request by geyslan**
### 1. Explain what the PR does

commit

    libbpf: bump to v1.1.0

### 3. Other comments

Fixes: #2899
- #2899

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
@geyslan wasn't there a PR from Roi already doing that ?

**Comment by geyslan** [comment]
> @geyslan wasn't there a PR from Roi already doing that ? I thought he said that in the weekly meeting, maybe I'm mistaken.

Their changes are beyond a bump https://github.com/aquasecurity/tracee/pull/2905.

This PR will be changed to get next libbpfgo tag to be released soon.

**Comment by geyslan** [comment]
Issues with kernels 5.4: https://github.com/aquasecurity/tracee/actions/runs/4493878758/jobs/7905802462

**Comment by geyslan** [comment]
@rafaeldtinoco I don't have access to those 5.4 images for testing.

**Comment by geyslan** [comment]
> I believe you do have access for Focal 5.4 both amd64 and arm64, but you don't have access to GKE image (adding now). Hopefully your ID is ....955980, if this is right, then you have been added to the GKE AMIs access list.

Thanks.

**Comment by geyslan** [comment]
> @geyslan bumping libbpf should trigger the bigger tests. That is controlled by the PR workflow. Could you change it so all tests run ?

Tried to re-run all workflow tests but no deal. Will rebase it doing a reword to trigger via a hash change.

**Comment by rafaeldtinoco** [comment]
Doesn't it touch `.gitmodules` ?

**Review by rafaeldtinoco — APPROVED** [review]
LGTM then.

**Comment by geyslan** [comment]
> Issues with kernels 5.4: https://github.com/aquasecurity/tracee/actions/runs/4493878758/jobs/7905802462

Well, this bump is causing the following failure in kernels 5.4:

```shell
root@ip-172-31-7-181:/home/ubuntu/tracee# ./dist/tracee-ebpf -log debug
{"L":"DEBUG","T":"2023-03-23T16:06:49.828Z","M":"OSInfo","VERSION":"\"20.04.5 LTS (Focal Fossa)\"","ID":"ubuntu","ID_LIKE":"debian","PRETTY_NAME":"\"Ubuntu 20.04.5 LTS\"","VERSION_ID":"\"20.04\"","VERSION_CODENAME":"focal","KERNEL_RELEASE":"5.4.0-137-generic","ARCH":"x86_64","origin":"urfave:pkg/cmd/urfave/urfave.go:64","calls":"GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-03-23T16:06:49.828Z","M":"RuntimeSockets: failed to register default","socket":"crio","error":"runtime.(*Sockets).Register: failed to register runtime socket stat /var/run/crio/crio.sock: no such file or directory","origin":"flags:pkg/cmd/flags/containers.go:47","calls":"PrepareContainers.func1() < Autodiscover.func1() < Autodiscover() < PrepareContainers() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-03-23T16:06:49.828Z","M":"RuntimeSockets: failed to register default","socket":"podman","error":"runtime.(*Sockets).Register: failed to register runtime socket stat /var/run/podman/podman.sock: no such file or directory","origin":"flags:pkg/cmd/flags/containers.go:47","calls":"PrepareContainers.func1() < Autodiscover.func1() < Autodiscover() < PrepareContainers() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-03-23T16:06:49.828Z","M":"OSInfo","security_lockdown":"none","origin":"urfave:pkg/cmd/urfave/urfave.go:137","calls":"GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-03-23T16:06:49.831Z","M":"BTF","bpfenv":false,"btfenv":false,"vmlinux":true,"origin":"initialize:pkg/cmd/initialize/bpfobject.go:41","calls":"BpfObject() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-03-23T16:06:49.831Z","M":"BPF: using embedded BPF object","origin":"initialize:pkg/cmd/initialize/bpfobject.go:70","calls":"BpfObject() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-03-23T16:06:49.840Z","M":"Unpacked CO:RE bpf object file into memory","origin":"initialize:pkg/cmd/initialize/bpfobject.go:145","calls":"unpackCOREBinary() < BpfObject() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-03-23T16:06:49.848Z","M":"Enricher","error":"containers.(*runtimeInfoService).Register: error registering enricher: unsupported runtime crio","origin":"containers:pkg/containers/containers.go:70","calls":"New() < (*Tracee).Init() < Runner.Run() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-03-23T16:06:49.849Z","M":"Enricher","error":"containers.(*runtimeInfoService).Register: error registering enricher: unsupported runtime podman","origin":"containers:pkg/containers/containers.go:80","calls":"New() < (*Tracee).Init() < Runner.Run() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"WARN","T":"2023-03-23T16:06:49.904Z","M":"libbpf: map '.rodata.str1.1': failed to create: Invalid argument(-22)"}
{"L":"WARN","T":"2023-03-23T16:06:49.904Z","M":"libbpf: failed to load object 'embedded-core'"}

End of events stream
Stats: {EventCount:0 EventsFiltered:0 NetCapCount:0 BPFLogsCount:0 ErrorCount:0 LostEvCount:0 LostWrCount:0 LostNtCapCount:0 LostBPFLogsCount:0}
{"L":"FATAL","T":"2023-03-23T16:06:49.905Z","M":"App","error":"cmd.Runner.Run: error initializing Tracee: ebpf.(*Tracee).Init: ebpf.(*Tracee).initBPF: ebpf.(*Tracee).initBPF.func1: failed to load BPF object: invalid argument"}
```

**Comment by rafaeldtinoco** [comment]
@geyslan 

I remember in the past we had to:

```
commit 9ba4e04 (tag: v0.4.4-libbpf-1.0.1, tag: helpers/v0.4.4)
Author: Rafael David Tinoco <rafaeldtinoco@gmail.com>
Date:   Tue Oct 25 11:16:27 2022

    fix: re-introduce memory bumping (#265)

    make libbpfgo to bump rlimits instead of relying in libbpf to do so.
```

because in some kernels libbpf wouldn't bump rlimits. I wonder if its related. No time to check now.

**Comment by rafaeldtinoco** [comment]
Yep, Im on it, I think its related to *strings, lets see.. results coming in a bit...

**Comment by geyslan** [comment]
### kernel NOT WORKING - 5.4

```shell
root@ip-172-31-7-181:/home/ubuntu/tracee# uname -a
Linux ip-172-31-7-181 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```shell
root@ip-172-31-7-181:/home/ubuntu/tracee# grep -i btf /boot/config-5.4.0-137-generic
CONFIG_VIDEO_SONY_BTF_MPX=m
CONFIG_DEBUG_INFO_BTF=y
```

```shell
root@ip-172-31-7-181:/home/ubuntu/tracee# grep -i bpf /boot/config-5.4.0-137-generic
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_UNPRIV_DEFAULT_OFF=y
CONFIG_IPV6_SEG6_BPF=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_BPFILTER=y
CONFIG_BPFILTER_UMH=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
CONFIG_BPF_KPROBE_OVERRIDE=y
CONFIG_TEST_BPF=m
```

**Comment by rafaeldtinoco** [comment]
Okay, found the offending commit, working on it...

**Comment by rafaeldtinoco** [comment]
This is the offending commit:

```
commit 3cd45b6
Author: Andrii Nakryiko <andrii@kernel.org>
Date:   Wed Oct 19 00:28:15 2022

    libbpf: only add BPF_F_MMAPABLE flag for data maps with global vars

    Teach libbpf to not add BPF_F_MMAPABLE flag unnecessarily for ARRAY maps
    that are backing data sections, if such data sections don't expose any
    variables to user-space. Exposed variables are those that have
    STB_GLOBAL or STB_WEAK ELF binding and correspond to BTF VAR's
    BTF_VAR_GLOBAL_ALLOCATED linkage.

    The overall idea is that if some data section doesn't have any variable that
    is exposed through BPF skeleton, then there is no reason to make such
    BPF array mmapable. Making BPF array mmapable is not a free no-op
    action, because BPF verifier doesn't allow users to put special objects
    (such as BPF spin locks, RB tree nodes, linked list nodes, kptrs, etc;
    anything that has a sensitive internal state that should not be modified
    arbitrarily from user space) into mmapable arrays, as there is no way to
    prevent user space from corrupting such sensitive state through direct
    memory access through memory-mapped region.

    By making sure that libbpf doesn't add BPF_F_MMAPABLE flag to BPF array
    maps corresponding to data sections that only have static variables
    (which are not supposed to be visible to user space according to libbpf
    and BPF skeleton rules), users now can have spinlocks, kptrs, etc in
    either default .bss/.data sections or custom .data.* sections (assuming
    there are no global variables in such sections).

    The only possible hiccup with this approach is the need to use global
    variables during BPF static linking, even if it's not intended to be
    shared with user space through BPF skeleton. To allow such scenarios,
    extend libbpf's STV_HIDDEN ELF visibility attribute handling to
    variables. Libbpf is already treating global hidden BPF subprograms as
    static subprograms and adjusts BTF accordingly to make BPF verifier
    verify such subprograms as static subprograms with preserving entire BPF
    verifier state between subprog calls. This patch teaches libbpf to treat
    global hidden variables as static ones and adjust BTF information
    accordingly as well. This allows to share variables between multiple
    object files during static linking, but still keep them internal to BPF
    program and not get them exposed through BPF skeleton.

    Note, that if the user has some advanced scenario where they absolutely
    need BPF_F_MMAPABLE flag on .data/.bss/.rodata BPF array map despite
    only having static variables, they still can achieve this by forcing it
    through explicit bpf_map__set_map_flags() API.

    Acked-by: Stanislav Fomichev <sdf@google.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Dave Marchevsky <davemarchevsky@fb.com>
    Link: https://lore.kernel.org/r/20221019002816.359650-3-andrii@kernel.org
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
```

and this is the upstream fix for it:

```
commit ce8d078
Author: Ludovic L'Hours <ludovic.lhours@gmail.com>
Date:   Sun Jan 8 18:20:18 2023

    libbpf: Fix map creation flags sanitization

    As BPF_F_MMAPABLE flag is now conditionnaly set (by map_is_mmapable),
    it should not be toggled but disabled if not supported by kernel.

    Fixes: 4fcac46c7e10 ("libbpf: only add BPF_F_MMAPABLE flag for data maps with global vars")
    Signed-off-by: Ludovic L'Hours <ludovic.lhours@gmail.com>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/r/20230108182018.24433-1-ludovic.lhours@gmail.com
    Signed-off-by: Martin KaFai Lau <martin.lau@kernel.org>
```

Meaning that the version `1.1.0` is no good for us without `commit ce8d078`. My suggestion is for us to bump both: libbpf and libbpfgo to that commit (instead of using the v1.1.0 tag).

@geyslan I'll let you handle that, I can review/approve the PRs.

**Comment by yanivagman** [comment]
I think we should stay with official libbpf versions.
Any reason to bump to v1.1.0 or can we stay with v1.0.1 until a newer libbpf version is released?

**Comment by geyslan** [comment]
> I think we should stay with official libbpf versions.

Since yesterday libbpfgo is already b2e29a1:

- https://github.com/aquasecurity/libbpfgo/issues/305

That fixed v1.1.0 https://github.com/libbpf/libbpf/commit/ce8d078ac762df56a8407456601debd25457672e issue which was a no go for tracee on 5.4 kernels.

> Any reason to bump to v1.1.0 or can we stay with v1.0.1 until a newer libbpf version is released?

The only concern is the daily test break against libbpfgo upstream. @rafaeldtinoco WDYT?

**Comment by geyslan** [comment]
@yanivagman, @rafaeldtinoco and I analyzed the range of commits from v1.0.1..v1.1.0 and we didn't find any commits that mattered. We assume we're fine keeping v1.0.1.

**Pull request merged**
