### PR TITLE
chore: migrate to golang-lru v2

### PR DESCRIPTION
**Pull request by NDStrahilevitz**
Upgrade `hashicorp/golang-lru` to v2.
This includes generics and further optimizations and fixes.

TODO: add pcaps tests to make sure it doesn't break.

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
@NDStrahilevitz Im sorry for the burden Nadav, could your rebase this ? I promise to test and merge it right as you do. Thanks!

**Comment by NDStrahilevitz** [comment]
@rafaeldtinoco Done :)

**Comment by rafaeldtinoco** [comment]
Seems to be working fine:

image

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Pull request merged**
