### PR TITLE
Upgrade libbpf, libbpfgo and other fixes

### PR DESCRIPTION
**Pull request by grantseltzer**
This is a few changes that will need to be merged before v0.8.2

commit ce7702428370dda82fe11fe71007f33febea75bb (HEAD -> upgrade-libbpf-libbpfgo-and-other-fixes, pfork/upgrade-libbpf-libbpfgo-and-other-fixes)
Author: grantseltzer <grantseltzer@gmail.com>
Date:   Thu Aug 25 11:26:22 2022 -0400

    Fix breaking change in upcoming release of libbpfgo
    
    Signed-off-by: grantseltzer <grantseltzer@gmail.com>

commit 8056f0b48e4845c250d4cfb03e2ab45c8892637e
Author: grantseltzer <grantseltzer@gmail.com>
Date:   Thu Aug 25 11:24:17 2022 -0400

    Upgrade to go 1.19 and multiple package upgrades
    
    - Upgrade to go 1.19
    - Upgrade go4.org/unsafe/assume-no-moving-gc (required for go version
      upgrade)
    - TEMPORARY replace line for libbpgo until its next release (w/ libbpf
      1.0 support)
    
    Signed-off-by: grantseltzer <grantseltzer@gmail.com>

commit 7965f2399553c0c6c1c11c2202ed628f194dd9c6
Author: grantseltzer <grantseltzer@gmail.com>
Date:   Thu Aug 25 11:23:57 2022 -0400

    Fix typo in doc
    
    Signed-off-by: grantseltzer <grantseltzer@gmail.com>

commit a026444ca1a0531468c9eff876c413048556b7ea
Author: grantseltzer <grantseltzer@gmail.com>
Date:   Thu Aug 25 11:23:39 2022 -0400

    Upgrade libbpf submodule to v1.0.0
    
    Signed-off-by: grantseltzer <grantseltzer@gmail.com>

### CODE REVIEW

**Comment by grantseltzer** [comment]
I will patch this PR once I cut a release of libbpfgo

**Comment by grantseltzer** [comment]
I've pushed the latest libbpfgo, fixed changes, and rebased, but now i'm getting a panic in integration tests locally. Investigating

**Comment by grantseltzer** [comment]
Ok I see the issue, fixing

**Review by rafaeldtinoco — COMMENTED** [review]
You upgrade to 1.19 and do multiple package upgrades but, yet, our baseline for everything/tests is still in 1.17 (and there is a Makefile check for go versions). Should we review all the go versioning (in all those cases as well ? I believe we should).

**Comment by grantseltzer** [comment]
> You upgrade to 1.19 and do multiple package upgrades but, yet, our baseline for everything/tests is still in 1.17 (and there is a Makefile check for go versions). Should we review all the go versioning (in all those cases as well ? I believe we should).

Hm, would all stakeholders be ready for that in this release? If not I suppose we can keep 1.17? I'm not sure there'd be any breaking changes.

**Comment by rafaeldtinoco** [comment]
> Hm, would all stakeholders be ready for that in this release? If not I suppose we can keep 1.17? I'm not sure there'd be any breaking changes.

Probably not as CNDR currently needs 1.17 and it might be good to keep it by default for 0.8.2 at least.

**Comment by rafaeldtinoco** [comment]
Closed on behalf of: https://github.com/aquasecurity/tracee/pull/2146

**Pull request closed without merging**
