### PR TITLE
feat(signatures): add simple proctree datasource envelope

### PR DESCRIPTION
**Pull request by AlonZivony**
### 1. Explain what the PR does

I donate this signatures helper code in the hope that it will help other people to use the process tree datasource.

07371088b **feat(signatures): add simple proctree datasource envelope**

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
This is actually the reason why I started the discussion about having data sources with generic types or having the package types to include the types of whatever we're saving there.

Like you do in this change, you wrap the type casting/checking, to make it easier to be used. I believe this change, for now, is a good change. Im just afraid of having this code not being used by anything hanging there and not tested.

I believe, besides having a simple unit testing (not sure is needed) but, maybe have a signature using the feature (and helper). Do you think we can open source a simple signature using process tree ? Or include a feature in one of the existing signatures ?

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Comment by AlonZivony** [comment]
> @AlonZivony
> 
> This is actually the reason why I started the discussion about having data sources with generic types or having the package types to include the types of whatever we're saving there.
> 
> Like you do in this change, you wrap the type casting/checking, to make it easier to be used. I believe this change, for now, is a good change. Im just afraid of having this code not being used by anything hanging there and not tested.
> 
> I believe, besides having a simple unit testing (not sure is needed) but, maybe have a signature using the feature (and helper). Do you think we can open source a simple signature using process tree ? Or include a feature in one of the existing signatures ?

Hmm I think we can add a feature of adding lineage to all signatures upon trigger for example.
Also, we can use this helper type now for the e2e test of the process tree. WDYT?

**Comment by rafaeldtinoco** [comment]
> Also, we can use this helper type now for the e2e test of the process tree. WDYT?

Yep, I would go for this **at least**. Because then if something brakes we will get on the tests right away.

**Pull request merged**
