### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by yanivagman**

### CODE REVIEW

**Comment by itaysk** [comment]
is this based on `go fmt -l` ? what was missing before that we didn't see these recommendations?

**Comment by yanivagman** [comment]
use gofmt without space (go fmt)

**Comment by yanivagman** [comment]
I didn't see all errors though (different gofmt version?)

**Comment by itaysk** [comment]
since lint commits are going to pollute the history, it's better to make sure once commit fixes all the issues once and for all.  
are you on go 1.15?

**Comment by yanivagman** [comment]
I'm on go 1.15.
Lint test passed on my repo:
https://github.com/yanivagman/tracee/actions

**Review by itaysk — APPROVED** [review]

**Pull request merged**
