### PR TITLE
Adding labels to Docker image

### PR DESCRIPTION
**Pull request by krol3**
Related https://github.com/aquasecurity/tracee/issues/391
Adding labels to Docker image

### CODE REVIEW

**Review by grantseltzer — APPROVED** [review]
This looks good to me!

Would there be a reason to add these ARG/LABELs to the dockerfiles in tracee-ebpf and tracee-rules ? Not that familiar with the relationship between them.

**Comment by krol3** [comment]
This ARG/LABEL will create the labels in the image. For example
`docker inspect tracee:latest`

```

            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2021-03-18T01:22:33Z",
                "org.label-schema.description": "Linux Runtime Security and Forensics using eBPF",
                "org.label-schema.name": "tracee",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-branch": "labels-docker",
                "org.label-schema.vcs-ref": "7492580",
                "org.label-schema.vcs-url": "https://github.com/aquasecurity/tracee",
                "org.label-schema.vendor": "Aqua Security",
                "org.label-schema.version": "test"
            }
        },
        "Architecture": "amd64",
```

**Comment by grantseltzer** [comment]
Ah got it, thanks for the clarification! Would the labels be appropriate for  [this dockerfile](https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/Dockerfile) as well?

**Comment by krol3** [comment]
I follow the labels created already by the golang release. For example. these are the trivy labels
```
LABEL org.label-schema.build-date=2021-02-08T10:20:47Z
LABEL org.label-schema.description=A Fast Vulnerability
LABEL org.label-schema.name=trivy
LABEL org.label-schema.schema-version=1.0
LABEL org.label-schema.vcs=https://github.com/aquasecurity/trivy
LABEL org.label-schema.vcs-ref=cdabe7fc9e74000911269228ebe3cb59f3879df4
LABEL org.label-schema.vendor=Aqua Security
LABEL org.label-schema.version=0.16.0
```

**Pull request merged**
