### PR TITLE
chore: add kernel 6.8 and 6.10 in matrix images

### PR DESCRIPTION
**Pull request by rscampos**
### 1. Explain what the PR does

d4524045e **chore: add kernel 6.8 and 6.10 in matrix images**

```
- Add kernel 6.8 and 6.10, both for x86_64 and aarch64;
- Both kernels are based on Ubuntu 24.04 LTS (codename Noble).
```

### CODE REVIEW

**Comment by geyslan** [comment]
https://github.com/aquasecurity/tracee/actions/runs/12352508128/job/34469702343?pr=4434#step:4:33

To avoid installing all by hand again I suggest you pick the latest image, set package providers, upgrade packages (and system), and finally set the desired kernel.

**Review by geyslan — APPROVED** [review]
LGTM

**Comment by rscampos** [comment]
@geyslan just added kernel 6.8 and 6.10 for arm64 :)

**Comment by geyslan** [comment]
> @geyslan just added kernel 6.8 and 6.10 for arm64 :)

Awesome, bring them in.

**Pull request merged**
