### PR TITLE
flags: logger: add libbpf log level flag

### PR DESCRIPTION
**Pull request by geyslan**
### 3. Other comments

Fixes: #3035

~~Currently, due to a libbpfgo [issue](https://github.com/aquasecurity/libbpfgo/issues/311), all libbpf output is being set as level 0 and tests won't work accordingly.~~

### CODE REVIEW

**Comment by NDStrahilevitz** [comment]
Is there a reason we would want to split off the libbpf log level from our own? I think it should just inherit tracee's log level instead of introducing the complexity of two separate log levels.

**Comment by geyslan** [comment]
> Is there a reason we would want to split off the libbpf log level from our own? I think it should just inherit tracee's log level instead of introducing the complexity of two separate log levels.

There's no reason, I agree with you. This PR will be reworked. Please take a look at https://github.com/aquasecurity/tracee/issues/2823#issuecomment-1492398582.

**Comment by geyslan** [comment]
The rework is ready for review.

**Comment by geyslan** [comment]
Closing since a lot changed. https://github.com/aquasecurity/tracee/issues/3035 will be tackled in another PR.

**Pull request closed without merging**
