### PR TITLE
Use the merged external and types module

### PR DESCRIPTION
**Pull request by AsafEitani**
completes #1454, solves #1312 and prepares for #1431

### CODE REVIEW

**Comment by NDStrahilevitz** [comment]
Personally, I think instead of going by this route:
#1460 (asaf pr) -> #1493 (my types pr) -> #1482 (event header refactor pr)

we could just do

#1493 -> #1482

or maybe even

1493 -> 1460 -> 1482

This is mostly so we can finalize the types for now. Either way, i'm fine with this, but I will note that in #1493 I've changed `trace.TraceeEvent` back to `trace.Event` (package name made me feel ok to do it).

**Comment by AsafEitani** [comment]
IDK how we ended up doing the same thing twice, but it doesn't really matters to me.
I do think that we should keep `TraceeEvent` as it really represent that, and not any generic event that we will have in the future from other sources. It will make it easier to differentiate between detect and trace.

The only thing that matters to me is that either this PR or #1482 will be merged soon.
Too bad we did double the work.

PS. @grantseltzer just merged the final restructure and this PR will need a massive rebase, which is exactly why I wanted to merge both PRs one after the other.
@NDStrahilevitz We can go with whatever you choose as long as we will be able to compile signatures separately from tracee ASAP.

**Comment by NDStrahilevitz** [comment]
About the name: how about `EbpfPayload`?

About the PR path we take I think let's just go with the shortest route which is #1493 -> #1482

**Comment by NDStrahilevitz** [comment]
@AsafEitani since #1482 basically does the same thing and was just merged I think this can be closed.

**Pull request closed without merging**
