### PR TITLE
engine: fix panic on waitgroup

### PR DESCRIPTION
**Pull request by josedonizetti**
### 1. Explain what the PR does

[Wait must be synchronized with the first Add.](https://go.dev/src/sync/waitgroup.go?s=1857:1892#L42) 

This seems to be the case here, as we call Add from inside the goroutine, for a short lived `tracee-rules` process there might  be a race between `checkCompletion` and `signatureStart` triggering the error reported on the issues https://github.com/aquasecurity/tracee/issues/3230 and https://github.com/aquasecurity/tracee/issues/3151

### CODE REVIEW

**Review by geyslan — COMMENTED** [review]
Makes sense. LGTM.

**Comment by yanivagman** [comment]
Didn't we want to merge this before the v0.15.1 release?

**Comment by OriGlassman** [comment]
Are you guys sure this can only happen by sending a SIGINT? This error was observed on a lambda (where it shouldn't have received a SIGINT)

**Comment by josedonizetti** [comment]
@OriGlassman It is not because of SIGINT, but a short-lived `tracee-rules`, which might happen due to different reasons, a signal as one of the issues, or if you are using it to analyze events from a file, maybe the file doesn't have enough events. 

The race seems to happen because we close the [`inputs.Tracee`](https://github.com/aquasecurity/tracee/blob/main/cmd/tracee-rules/input.go#L129) channel to quickly, due to the lack of events. Triggering the stop of the engine [`consumeSources`](https://github.com/aquasecurity/tracee/blob/main/pkg/signatures/engine/engine.go#L197) loop, which starts a [`Wait`](https://github.com/aquasecurity/tracee/blob/main/pkg/signatures/engine/engine.go#L137) op on the waitgroup, but the go routines for the signatures still didn't had the time to setup the [waitgroup](https://github.com/aquasecurity/tracee/blob/main/pkg/signatures/engine/engine.go#L137).


A simple way to simulate it is by creating a file with just one event:

test.json
```
{"timestamp":1686775048087416430,"threadStartTime":1686754169760481353,"processorId":7,"processId":1,"cgroupId":10999,"threadId":12,"parentProcessId":3293,"hostProcessId":3374,"hostThreadId":3480,"hostParentProcessId":3293,"userId":65534,"mountNamespace":4026533123,"pidNamespace":4026533127,"processName":"prometheus","hostName":"josedonizetti-x","containerId":"632b2b487644f2627ffd0fc148b0c83b1efd43a8a2236975071fb85ae932d922","container":{"id":"632b2b487644f2627ffd0fc148b0c83b1efd43a8a2236975071fb85ae932d922"},"kubernetes":{},"eventId":"2010","eventName":"net_packet_http_request","matchedPolicies":[""],"argsNum":2,"returnValue":0,"syscall":"write","stackAddresses":[0],"contextFlags":{"containerStarted":true,"isCompat":false},"args":[{"name":"metadata","type":"trace.PktMeta","value":{"src_ip":"127.0.0.1","dst_ip":"127.0.0.1","src_port":46122,"dst_port":9100,"protocol":6,"packet_len":336,"iface":"any"}},{"name":"http_request","type":"trace.ProtoHTTPRequest","value":{"method":"GET","protocol":"HTTP/1.1","host":"localhost:9100","uri_path":"/metrics","headers":{"Accept":["application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0.4;q=0.5,*/*;q=0.1"],"Accept-Encoding":["gzip"],"User-Agent":["Prometheus/2.44.0"],"X-Prometheus-Scrape-Timeout-Seconds":["5"]},"content_length":0}}]}
```

Then, starting `tracee-rules` to analyze it in a loop:

```
while true; do sudo ./dist/tracee-rules --allcaps --input-tracee format:json --input-tracee file:./test.log 2>&1 | grep -v info; done
```

It should hit the issue every X time that we run `tracee-rules`. 

After several tests, this PR indeed fixes the bug.

**Comment by josedonizetti** [comment]
@yanivagman @rafaeldtinoco @geyslan as per the comment above ˆˆ, the bug is indeed fixed by this change.

**Review by geyslan — APPROVED** [review]

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Pull request merged**
