### PR TITLE
feat: add more info to logger debug level

### PR DESCRIPTION
**Pull request by geyslan**
feat: add more info to logger debug level
    
    This removes the pkg, file and line fields from log entry, replacing
    them with origin which has the format:
    
    "origin":"pkg:relative/path/to/file:line"
    
    e.g.:
    
    "origin":"proc:pkg/utils/proc/ns.go:40"
    
    The file path is now clickable in most editors and terminals.
    
    This also introduces to debug level "calls" field, which is a custom
    call trace back to the logger call.
    
    e.g.:
    
    "calls":"GetMountNSFirstProcesses() < (*Tracee).Init.func1() <
    (*Capabilities).Requested() < (*Tracee).Init() < Runner.Run() <
    main.func1() < (*App).RunContext() < (*App).Run() < main()"

## Initial Checklist

- [x] There is an issue describing the need for this PR.

Fixes: #2568

## Type of change

- [x] New feature (non-breaking change adding functionality).

## How Has This Been Tested?

```shell
sudo ./dist/tracee -t comm=uname -log debug               
{"L":"DEBUG","T":"2023-02-09T13:59:32.585-0300","M":"osinfo","ID_LIKE":"arch","BUILD_ID":"rolling","KERNEL_RELEASE":"5.15.91-1-MANJARO","ARCH":"x86_64","PRETTY_NAME":"\"Manjaro Linux\"","ID":"manjaro","origin":"urfave:pkg/cmd/urfave/urfave.go:54","calls":"GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.585-0300","M":"RuntimeSockets: failed to register default","socket":"containerd","error":"failed to register runtime socket stat /var/run/containerd/containerd.sock: no such file or directory","origin":"flags:pkg/cmd/flags/containers.go:47","calls":"PrepareContainers.func1() < Autodiscover.func1() < Autodiscover() < PrepareContainers() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.585-0300","M":"RuntimeSockets: failed to register default","socket":"crio","error":"failed to register runtime socket stat /var/run/crio/crio.sock: no such file or directory","origin":"flags:pkg/cmd/flags/containers.go:47","calls":"PrepareContainers.func1() < Autodiscover.func1() < Autodiscover() < PrepareContainers() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.585-0300","M":"RuntimeSockets: failed to register default","socket":"podman","error":"failed to register runtime socket stat /var/run/podman/podman.sock: no such file or directory","origin":"flags:pkg/cmd/flags/containers.go:47","calls":"PrepareContainers.func1() < Autodiscover.func1() < Autodiscover() < PrepareContainers() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.585-0300","M":"osinfo","security_lockdown":"none","origin":"urfave:pkg/cmd/urfave/urfave.go:118","calls":"GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.587-0300","M":"BTF","bpfenv":false,"btfenv":false,"vmlinux":true,"origin":"initialize:pkg/cmd/initialize/bpfobject.go:39","calls":"BpfObject() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.587-0300","M":"BPF: using embedded BPF object","origin":"initialize:pkg/cmd/initialize/bpfobject.go:68","calls":"BpfObject() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.590-0300","M":"unpacked CO:RE bpf object file into memory","origin":"initialize:pkg/cmd/initialize/bpfobject.go:143","calls":"unpackCOREBinary() < BpfObject() < GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.590-0300","M":"Enricher","error":"error registering enricher: unsupported runtime containerd","origin":"containers:pkg/containers/containers.go:64","calls":"New() < (*Tracee).Init() < Runner.Run() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.590-0300","M":"Enricher","error":"error registering enricher: unsupported runtime crio","origin":"containers:pkg/containers/containers.go:68","calls":"New() < (*Tracee).Init() < Runner.Run() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
{"L":"DEBUG","T":"2023-02-09T13:59:32.590-0300","M":"Enricher","error":"error registering enricher: unsupported runtime podman","origin":"containers:pkg/containers/containers.go:78","calls":"New() < (*Tracee).Init() < Runner.Run() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
```

### CODE REVIEW

**Comment by geyslan** [comment]
If `calls` field gets approved, maybe it could be inverted, like:

`"calls":"GetMountNSFirstProcesses() < (*Tracee).Init.func1() < (*Capabilities).Requested() < (*Tracee).Init() < Runner.Run() < main.func1() < (*App).RunContext() < (*App).Run() < main()"`

instead of:

`"calls":"main() > (*App).Run() > (*App).RunContext() > main.func1() > Runner.Run() > (*Tracee).Init() > (*Capabilities).Requested() > (*Tracee).Init.func1() > GetMountNSFirstProcesses()"`

Waiting feedback on that.

**Review by NDStrahilevitz — APPROVED** [review]
Nice, LGTM

**Comment by rafaeldtinoco** [comment]
Spoke to @geyslan about this one. Asked for "

```
"origin":"proc:/home/gg/code/tracee/pkg/utils/proc/ns.go:40"
```

to have "/home/gg/code" removed from the info.

Also asked for this to be added to 0.11.1 milestone and then we can merge before the next bugfix release.

**Comment by geyslan** [comment]
> Spoke to @geyslan about this one. Asked for "
> 
> ```
> "origin":"proc:/home/gg/code/tracee/pkg/utils/proc/ns.go:40"
> ```
> 
> to have "/home/gg/code" removed from the info.
> 

Done.

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Pull request merged**
