### PR TITLE
Use filepath.WalkDir() to scan for signatures

### PR DESCRIPTION
**Pull request by jan0ski**
👋 This PR should address #501 .  Only concern I have is that I'm not sure how to test `findGoSigs()`, as go signatures were also left out of [`Test_getSignatures()`](https://github.com/aquasecurity/tracee/blob/main/tracee-rules/signature_test.go#L12).  Happy to add that coverage with some guidance!

* Refactor `findRegoSigs()` and `findGoSigs()` to utilize `filepath.WalkDir()` to recursively scan for signatures
* Add tests for `findRegoSigs()`

### CODE REVIEW

**Comment by itaysk** [comment]
Thanks @jan0ski please see https://github.com/aquasecurity/tracee/pull/893/ and rebase to include those changes.

**Comment by itaysk** [comment]
@jan0ski sorry but you'll need to rebase again after #903

**Comment by josedonizetti** [comment]
@jan0ski  I think @itaysk meant https://github.com/aquasecurity/tracee/pull/906, sorry about the rework.

**Comment by jan0ski** [comment]
Should be all up to date now.  Let me know if anything's missing.

**Review by grantseltzer — APPROVED** [review]
@jan0ski Sorry about the delay in reviewing, this LGTM! Thank you very much!

**Pull request merged**
