### PR TITLE
ebpf: add a new required dependency field.

### PR DESCRIPTION
**Pull request by NDStrahilevitz**
## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.

## Description (git log)

Marking an event as required will make it so failing to attach it's probe will fail tracee.
Otherwise, tracee will continue to load as usual and simply log the failure.
Now events can be loaded with partial dependencies.

Fixes: #1622

## Type of change

New feature (non-breaking change adding functionality).

I've marked event dependencies that I think should be required as such, but I'm not 100% confident that I got it right on the first go. So anyone reviewing should pay extra attention to that :)

In addition, the previously named "essential" events have been marked as required, and a function for handling all initial required events was extracted out of `New` into `initRequiredEvents`. There may also be edge cases there to watch for.

## How Has This Been Tested?

This hasn't been tested yet. It will be tested on a reported GKE environment where tracee failed to load the `VfsWritev` event. After testing that `magic_write` can be loaded there I will report back here.

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented all functions/methods created explaining what they do.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Comment by yanivagman** [comment]
I think that what should be marked as required or not is the probe, and not the event.
If an event was chosen as a dependency of another event, the meaning is that we must successfully load and attach that event, otherwise, it shouldn't be marked as a dependency.
On the other hand, some probes of an event may be required, while other not. One example is vfs_writev probe for magic_write, and another example is when we will have probes that depend on some bpf features that only exist on newer kernels, we might choose if it is a requirement or not for the event.

**Comment by NDStrahilevitz** [comment]
> I think that what should be marked as required or not is the probe, and not the event. If an event was chosen as a dependency of another event, the meaning is that we must successfully load and attach that event, otherwise, it shouldn't be marked as a dependency. On the other hand, some probes of an event may be required, while other not. One example is vfs_writev probe for magic_write, and another example is when we will have probes that depend on some bpf features that only exist on newer kernels, we might choose if it is a requirement or not for the event.

Agreed, so I'll post here what we discussed offline.
You plan to flatten the probe dependencies away from the event dependencies. 
Then this PR (or yours) can introduce a `probeDependency` struct where we can mark a probes as require instead, so we could have a probe as required for one event and unrequired for another (for example vfs_writev and magic_write). 

So this PR will wait on that.

**Review by rafaeldtinoco — APPROVED** [review]
I'm approving but left couple of comments so you can chose to accept if you think they're worth. Overall change looks good and I like the fact that we're auto-loading all programs (we will errors independently of given cmdline).

I see that you are mentioning we should load (or not) programs based on existing kernel features (and chose to attach or not based on current config, that might do reconfigs). Check also tracee.go for network programs "autoload" set to false. Maybe you want to get rid of that as well (so network programs are also always loaded).

**Comment by yanivagman** [comment]
@NDStrahilevitz this PR needs to be rebased on main as probes are now flatten (like we previously discussed)

**Comment by NDStrahilevitz** [comment]
I am closing this in favor of the fix i've done in #1791

**Pull request closed without merging**
