### PR TITLE
chore: make analyze mode work with sigs of sigs

### PR DESCRIPTION
**Pull request by geyslan**
`analyze` mode wasn't aware of signature's selected events working as signatures. Now it also loads all of the selected.

### 1. Explain what the PR does

ef6441f57 **chore: make analyze mode work with sigs of sigs**

### CODE REVIEW

**Comment by geyslan** [comment]
Tested with current signatures (which depend only on base events) and still works.

Be aware that in case selected are sigs, the input must include events from all base events that are selected by the selected signatures themselves.

**Comment by NDStrahilevitz** [comment]
@geyslan From my end, I feel like I'm missing context on how this solved the issue, and what didn't work in the first place. Because on its face i'd assume that:
1. signatures are converted to event definitions
2. a sig-on-sig selector filters for these event names created in step 1
3. therefore signatures selecting for signatures should work

So i'm not sure what in these steps was faulty and how this code fixes it.

**Comment by geyslan** [comment]
@NDStrahilevitz sorry, this should be closed already, it was only raised to help the team on debugging. There's another PR that continued this. https://github.com/aquasecurity/tracee/pull/4314

**Comment by geyslan** [comment]
Anyway, this piece only loaded the all other required sigs of a sig that declares them as Selected. Without it tracee warned about the missing sigs.

**Pull request closed without merging**
