### PR TITLE
recomission integration tests

### PR DESCRIPTION
**Pull request by NDStrahilevitz**
## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

```
integration: recomission the tests
    
    Integration tests were  previously skipped and as such unmaintained
    and were broken over time.
    Fix the tests by redesigning them to locally run tracee.
```

Fixes: #2005 

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [x] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## How Has This Been Tested?

Run tests locally by running:
`sudo env "PATH=$PATH" make test-integration`

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented all functions/methods created explaining what they do.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix, or feature, is effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
@grantseltzer fyi

**Review by rafaeldtinoco — COMMENTED** [review]
1. I think we should move tests/tracee-tester to an external branch (due to https://github.com/aquasecurity/tracee/issues/1949) and have an action in that new branch that creates "tracee-tester" docker image and publishes it. This way we can add more tests to it (there) according to the things we want to this in tracee (here).

2. I have also played a bit with reorganizing Makefile and adding some flags to the test targets (https://gist.github.com/rafaeldtinoco/468998d513c9a61426d239527c6b4287) and got the following **several** data races for `integration_test_.go`:

image

I believe that is because of parallel calls of `startTracee` for the multiple testCases.

**Comment by NDStrahilevitz** [comment]
> 1. I think we should move tests/tracee-tester to an external branch (due to #1949) and have an action in that new branch that creates "tracee-tester" docker image and publishes it. This way we can add more tests to it (there) according to the things we want to this in tracee (here).
> 2. I have also played a bit with reorganizing Makefile and adding some flags to the test targets (https://gist.github.com/rafaeldtinoco/468998d513c9a61426d239527c6b4287) and got the following **several** data races for `integration_test_.go`:
> 
> image
> 
> I believe that is because of parallel calls of `startTracee` for the multiple testCases.

1. Is it in the scope of this PR or just a comment? Because we don't really use tracee-tester here, but it could be an alternative approach
2. Yeah the makefile command I had to tailor specifically, and I also noticed at some point that parallelism was causing issues, which makes sense since a tracee instance would "steal" events from another (this was theoretically a problem also with the previous version, which could make tests flaky). That's why I added `-p 1`, and why testing with `-race` breaks it.

**Comment by rafaeldtinoco** [comment]
> * Is it in the scope of this PR or just a comment? Because we don't really use tracee-tester here, but it could be an alternative approach

I thought about saying it because of the "tests" directory. Didnt mean for this PR, sorry for not mentioning it.

> * Yeah the makefile command I had to tailor specifically, and I also noticed at some point that parallelism was causing issues, which makes sense since a tracee instance would "steal" events from another (this was theoretically a problem also with the previous version, which could make tests flaky). That's why I added `-p 1`, and why testing with `-race` breaks it.

Hum, ok. If -p1 fixes that I'm fine then =). Would you mind applying: https://gist.github.com/rafaeldtinoco/468998d513c9a61426d239527c6b4287 (without the race for this test) then ? Quick code replacement only.

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Pull request merged**
