### PR TITLE
Remove old builder files, move READMEs to cmd for tracee-ebpf and tracee-rules

### PR DESCRIPTION
**Pull request by grantseltzer**
Signed-off-by: grantseltzer <grantseltzer@gmail.com>

### CODE REVIEW

**Comment by yanivagman** [comment]
Shouldn't we also remove the deprecated tests from the pipeline in this PR?

**Comment by rafaeldtinoco** [comment]
Checking this now...

**Comment by rafaeldtinoco** [comment]
I have proposed 2 other patches on top of yours:

https://github.com/grantseltzer/tracee/pull/16

If you chose to accept I think we're good for the new building system.

**Review by yanivagman — APPROVED** [review]
LGTM!

**Comment by rafaeldtinoco** [comment]
I believe you should rebate the patched removing the merge request commit. Then you can force push and merge and commit

**Pull request merged**
