### PR TITLE
trace: add container and pod data to event

### PR DESCRIPTION
**Pull request by NDStrahilevitz**
This is in preparation for #1572

Also a good opportunity to discuss the new enrichment fields and if more are required for initial implementation.

### CODE REVIEW

**Review by rafaeldtinoco — COMMENTED** [review]
I haven't replied yet because I believe there was a meaningful reason for this struct to be flat (regarding possible padding and the fact this data comes from perf buffer shared memory).

@yanivagman could you confirm this thought here ?

**Comment by yanivagman** [comment]
> I haven't replied yet because I believe there was a meaningful reason for this struct to be flat (regarding possible padding and the fact this data comes from perf buffer shared memory).
> 
> @yanivagman could you confirm this thought here ?

Actually we now have the bufferdecoder that takes care of reading the bytes from the buffer (using the protocol's Context struct in that case), and this struct is what tracee-ebpf generates as an output.

LGTM!

**Review by yanivagman — APPROVED** [review]

**Comment by NDStrahilevitz** [comment]
I've flattened the struct to simplify usage later down the line (anonymous structs don't play nicely in go sometimes). We can merge this now @yanivagman

**Comment by yanivagman** [comment]
> I've flattened the struct to simplify usage later down the line (anonymous structs don't play nicely in go sometimes). We can merge this now @yanivagman

Ok, let's wait for @rafaeldtinoco to approve and merge as he requested a review on this

**Comment by rafaeldtinoco** [comment]
> Ok, let's wait for @rafaeldtinoco to approve and merge as he requested a review on this

I was being pro-active only =) sorry. I was waiting for the final checks to merge it.

**Pull request merged**
