### PR TITLE
chore: move syscaller to dist

### PR DESCRIPTION
**Pull request by geyslan**
### 1. Explain what the PR does

dc068334 **chore: move syscaller to dist** _<sub>(2023/jun/26) Geyslan Gregório \<geyslan@gmail.com\></sub>_

```
This commit moves syscaller to dist.

This also makes integration tests don't fail if not run as root. Now,
they will just skip the tests that require root privileges.
```

### 2. Explain how to test it

`make integration-test`
`sudo make integration-test`

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
@geyslan I noticed that I can't vscode "run all tests" because of integration root needs. Is there a way we can "bypass" tests if not root, instead of failing ? This way I can use that feature in vscode (and we still can test integration using root in other places). WDYT ?

**Comment by geyslan** [comment]
> @geyslan I noticed that I can't vscode "run all tests" because of integration root needs. Is there a way we can "bypass" tests if not root, instead of failing ? This way I can use that feature in vscode (and we still can test integration using root in other places). WDYT ?

Let me give a try. Back soon.

**Comment by geyslan** [comment]
Doable. Changing the behaviour.

```
=== RUN   Test_EventFilters
    tracee.go:229: ***** Test_EventFilters must be run as ROOT *****
--- SKIP: Test_EventFilters (0.00s)
=== RUN   Test_ParseCmd
--- PASS: Test_ParseCmd (0.00s)
=== RUN   Test_InitNamespacesEvent
    tracee.go:229: ***** Test_InitNamespacesEvent must be run as ROOT *****
--- SKIP: Test_InitNamespacesEvent (0.00s)
PASS
ok      github.com/aquasecurity/tracee/tests/integration        0.053s
?       github.com/aquasecurity/tracee/tests/integration/cpu    [no test files]
=== RUN   Test_callsys
--- PASS: Test_callsys (0.00s)
=== RUN   Test_changeOwnComm
--- PASS: Test_changeOwnComm (0.00s)
PASS
ok      github.com/aquasecurity/tracee/tests/integration/syscaller/cmd  0.031s
```

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Comment by rafaeldtinoco** [comment]
Cool. It skips the tests now ... and I just realized that:

image

Ubuntu's have this "problem" about "/usr/bin" being "/bin", so we should consider both (but its not related to this PR).

**Pull request merged**
