### PR TITLE
tracee: support external BTF files

### PR DESCRIPTION
**Pull request by rafaeldtinoco**
1. start using libbpfgo initial btfinfo helper
2. allow external BTF files through TRACEE_BTF_FILE env variable
3. execution decisions based on available environment

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
This merge can only be done after merge:

https://github.com/aquasecurity/libbpfgo/pull/53

and it is rebased on top of:

https://github.com/aquasecurity/tracee/pull/926

So, once pull #926 is accepted and pull #53 of libbpfgo is accepted this can be rebased and merged.

But it can be reviewed already =).

**Comment by yanivagman** [comment]
Please rebase on main first.
There are some changes here that were already merged.

**Comment by yanivagman** [comment]
Do you plan to address #833 here or in another PR?

**Comment by rafaeldtinoco** [comment]
> Do you plan to address #833 here or in another PR?

Another. Let's say that one is the 'big work' using automated BTFHUB when we define the API. I'll document this there.

**Comment by rafaeldtinoco** [comment]
Closing this and will submit a new one using https://github.com/aquasecurity/libbpfgo/pull/53 and https://github.com/aquasecurity/tracee/pull/926 that are now merged.

**Pull request closed without merging**
