### PR TITLE
Add utilization of bpf_probe_read_[kernel/user](_str)

### PR DESCRIPTION
**Pull request by cdelzotti**
Replaces old `bpf_probe_read(_str)` functions with new `bpf_probe_read_[user/kernel](_str)`.
It is safer as libbpf will automatically fall back to the old functions if unsupported.

Signed-off-by: Clément Delzotti <elk1ns@outlook.fr>

## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

Replaces old bpf_probe_read(_str) functions with new bpf_probe_read\_\[user/kernel\]\(_str\).
It is safer as libbpf will automatically fall back to the old functions if unsupported.

Fixes: #559 

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [x] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [ ] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Comment by yanivagman** [comment]
> Hmm, GitHub checks show an error while running `go test -v -run "TestTraceeSignatures" ./tests/e2e/e2e_test.go -tracee-image-ref "tracee:full" -tracee-tester-image-ref "aquasec/tracee-tester:latest" -tracee-signatures "TRC-2"`, but I can't reproduce the error by running the command locally

What was the error?

**Comment by cdelzotti** [comment]
> > Hmm, GitHub checks show an error while running `go test -v -run "TestTraceeSignatures" ./tests/e2e/e2e_test.go -tracee-image-ref "tracee:full" -tracee-tester-image-ref "aquasec/tracee-tester:latest" -tracee-signatures "TRC-2"`, but I can't reproduce the error by running the command locally
> 
> What was the error?

Didn't take note of it, sorry. It seemed it was related to "execve".

**Comment by rafaeldtinoco** [comment]
Alright, we have big conflicts for `add_u64_elements_to_buf()` now after recent changes. I also think we should have an issue for this and only accomplish it when dropping non CO-RE code (soon), so we can make sure all remaining CO-RE code uses the correct/recent helpers (this is not the only case that will need updates I'm afraid).

If you both agree, we could close this and keep issue #559 opened and tied to https://github.com/aquasecurity/tracee/issues/1651

**Comment by cdelzotti** [comment]
> Alright, we have big conflicts for `add_u64_elements_to_buf()` now after recent changes. I also think we should have an issue for this and only accomplish it when dropping non CO-RE code (soon), so we can make sure all remaining CO-RE code uses the correct/recent helpers (this is not the only case that will need updates I'm afraid).
> 
> If you both agree, we could close this and keep issue #559 opened and tied to #1651

That's fine for me :+1:

**Pull request closed without merging**
