### PR TITLE
perf: benchmark improve sig GetMetadata

### PR DESCRIPTION
**Pull request by rscampos**
### 1. Explain what the PR does

cf550d1d3 **perf: benchmark improve sig GetMetadata**

```
In the signature interface, the GetMetadata method is frequently called.
Currently, every time the method is called, memory is allocated for
metadata. Two alternative methods were evaluated: using metadata 1) with
sync.Once and 2) statically.
```

### 2. Explain how to test it

> GOOS=linux CC=clang GOARCH=arm64 CGO_CFLAGS="-I/vagrant/dist/libbpf -I/vagrant/3rdparty/libbpf/include/uapi" CGO_LDFLAGS="-L/vagrant/dist/libbpf/obj -lbpf " go test -benchmem -run=^$ -bench ^BenchmarkEngineMultipleMethodsGetMetadata$ github.com/aquasecurity/tracee/pkg/signatures/benchmark -benchtime=10000x

### 3. Other comments

```
current_method           	    10000            696962 ns/op          581334 B/op       5012 allocs/op
method_1_(sync.once)     	    10000            577382 ns/op          213181 B/op       2011 allocs/op
method_2_(statically)   	    10000            570819 ns/op          213310 B/op       2012 allocs/op
```

Using sync.Once or a static variable, we achieved approximately a 17% improvement compared to our current method, which allocates memory each time GetMetadata() is called.

### CODE REVIEW

**Comment by rscampos** [comment]
@geyslan right now I'm doing some tests to see if we have any RSS improvement

**Comment by geyslan** [comment]
Currently running a release snapshot, so the tests might be tainted. As soon as it finish I'll be bench-marking this PR.

**Comment by geyslan** [comment]
👍🏼 

```
Running tool: /home/gg/.goenv/versions/1.22.4/bin/go test -benchmem -run=^$ -tags ebpf -bench ^BenchmarkEngineMultipleMethodsGetMetadata$ github.com/aquasecurity/tracee/pkg/signatures/benchmark -benchtime=10000x

goos: linux
goarch: amd64
pkg: github.com/aquasecurity/tracee/pkg/signatures/benchmark
cpu: AMD Ryzen 9 7950X 16-Core Processor            
BenchmarkEngineMultipleMethodsGetMetadata/Performance_sig_GetMetadata()_-_current_method-32         	   10000	    757885 ns/op	  585829 B/op	    5013 allocs/op
BenchmarkEngineMultipleMethodsGetMetadata/Performance_sig_GetMetadata()_-_method_1_(sync.once)-32   	   10000	    533656 ns/op	  217610 B/op	    2012 allocs/op
BenchmarkEngineMultipleMethodsGetMetadata/Performance_sig_GetMetadata()_-_method_2_(statically)-32  	   10000	    532702 ns/op	  217697 B/op	    2012 allocs/op
PASS
ok  	github.com/aquasecurity/tracee/pkg/signatures/benchmark	42.362s
```

**Review by geyslan — APPROVED** [review]
LGTM

**Pull request merged**
