### PR TITLE
Add AVD link from detection docs

### PR DESCRIPTION
**Pull request by grantseltzer**
Signed-off-by: grantseltzer <grantseltzer@gmail.com>

## Initial Checklist

- [ ] There is an issue describing the need for this PR.
- [ ] Git log contains summary of the change.
- [ ] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

Add AVD links to rules page

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## How Has This Been Tested?

Tests being included in this PR:

- [ ] Test File A
- [ ] Test File B

Reproduce the test by running:

- command 01
- command 02

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [ ] My code follows the style guidelines (C and Go) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [ ] Subject starts with "subsystem|file: description".
- [ ] Do not end the subject line with a period.
- [ ] Limit the subject line to 50 characters.
- [ ] Separate subject from body with a blank line.
- [ ] Use the imperative mood in the subject line.
- [ ] Wrap the body at 72 characters.
- [ ] Use the body to explain what and why instead of how.

### CODE REVIEW

**Review by josedonizetti — COMMENTED** [review]
@grantseltzer aren't we supposed to add the AVDs to https://aquasecurity.github.io/tracee/v0.9/docs/detecting/rules/?

**Comment by grantseltzer** [comment]
@josedonizetti That's what I had originally but after talking to Itay I
realized it'd make more sense to have one link instead of maintaining all
individual links since they're autogenerated.

**Comment by josedonizetti** [comment]
@grantseltzer That makes sense, but this seems too hidden. I really like the info on avd, would like to see it more clearer on the docs. Would it make sense to also have a section for it under Docs? So it is a menu link with a little introduction and the link to the database?  WDYT?

**Comment by grantseltzer** [comment]
> @grantseltzer That makes sense, but this seems too hidden. I really like the info on avd, would like to see it more clearer on the docs. Would it make sense to also have a section for it under Docs? So it is a menu link with a little introduction and the link to the database? WDYT?

That sounds like a great idea, I'll try that

**Comment by itaysk** [comment]
do we need both "AVD" and "available rules" entries in the docs? seems redundant no? I thought we'd just replace the rules table with a link to AVD

**Comment by josedonizetti** [comment]
@itaysk Although I like AVD, navigating through it requires a lot of clicks, didn't find a simple way to see all tracee rules listed at once, the main page shows rules per category, requiring clicks back and forth to navigate. So I would still keep a brief list of available rules.

**Comment by itaysk** [comment]
ok. so if we keep the sigs page, we can link to AVD from there right? (like the first version)
also need to remember to update this page with sigs changes

**Comment by rafaeldtinoco** [comment]
@josedonizetti I'll let you review and merge this one once you're good.

**Comment by josedonizetti** [comment]
@grantseltzer mind tackling Itay's comment?

**Comment by grantseltzer** [comment]
@josedonizetti I believe I did,  I added the AVD section to rules.md, I thought that's what he had in mind.

**Pull request merged**
