### PR TITLE
fix: chore: bump Go to 1.19

### PR DESCRIPTION
**Pull request by geyslan**
Bump Go to 1.19 as a complement of #2633.

Fixes: #2677

## Initial Checklist

- [x] There is an issue describing the need for this PR.

Fixes:

- #2677

## Type of change

- [x] Bug fix (non-breaking change fixing an issue, preferable).

### CODE REVIEW

**Comment by NDStrahilevitz** [comment]
We need to remove `ioutil` usage for thiss.

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Comment by rafaeldtinoco** [comment]
@geyslan 

image

looks like static-check with go1.19 fails when checking types package.

**Review by rafaeldtinoco — CHANGES_REQUESTED** [review]
needs fixing

**Comment by geyslan** [comment]
Close as solved by https://github.com/aquasecurity/tracee/pull/2679

**Pull request closed without merging**
