### PR TITLE
[FEAT] logger: debug output enrichment

### PR DESCRIPTION
**Pull request by geyslan**
## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.

## Description (git log)

72c38284 logger: enrich debug level logs
ffa109a0 logger: refactor

Fixes: #2248 

## Type of change

- [x] Code refactor (code improvement and/or code removal)
- [x] New feature (non-breaking change adding functionality).

## How Has This Been Tested?

```shell
❯ sudo TRACEE_LOGGER_LVL=debug ./dist/tracee-ebpf -t comm=ls
{"level":"debug","ts":1666192669.9143562,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"BUILD_ID","OS_KERNEL_RELEASE":"rolling"}
{"level":"debug","ts":1666192669.9146245,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"PRETTY_NAME","OS_KERNEL_RELEASE":"\"Manjaro Linux\""}
{"level":"debug","ts":1666192669.9146755,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"KERNEL_RELEASE","OS_KERNEL_RELEASE":"5.15.74-3-MANJARO"}
{"level":"debug","ts":1666192669.9147034,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"ARCH","OS_KERNEL_RELEASE":"x86_64"}
{"level":"debug","ts":1666192669.9147112,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"ID","OS_KERNEL_RELEASE":"manjaro"}
{"level":"debug","ts":1666192669.9147198,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"ID_LIKE","OS_KERNEL_RELEASE":"arch"}
{"level":"debug","ts":1666192669.9160993,"msg":"osinfo","pkg":"main","file":"main.go","line":152,"security_lockdown":"none"}
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
```

### CODE REVIEW

**Review by josedonizetti — COMMENTED** [review]
@geyslan why export `CallerInfo`, `CallerPackage`, and `CallerFile` if no one is using it?

**Comment by geyslan** [comment]
> @geyslan why export `CallerInfo`, `CallerPackage`, and `CallerFile` if no one is using it?

@josedonizetti 

After our yesterday discussion, I thought that even if not at debug level the user of the logger could want to use this information as key/values for a Info or Warn level like:

`logger.Warn("not expected behaviour", "line", logger.CallerLine())`

I know, it's a information intrinsic to debug level, however, if one needs it, it's available now for any case. Let me know what you both think. @rafaeldtinoco

**Review by josedonizetti — APPROVED** [review]
@geyslan IMO we should not try to predict what funcs will be needed, and add methods as the necessity appears, if we ever need those methods for a use case, we add them. But if others agree with adding them here, no problem for me. :)

**Comment by geyslan** [comment]
> @geyslan IMO we should not try to predict what funcs will be needed, and add methods as the necessity appears, if we ever need those methods for a use case, we add them. But if others agree with adding them here, no problem for me. :)

I agree with you. As this is not a priority, I would like to wait others to state about it before merge or remove the CallerInfo(), CallerPackage(), CallerFile() and CallerLine().

Thanks for reviewing this.

**Comment by geyslan** [comment]
>

**Comment by geyslan** [comment]
> > @geyslan IMO we should not try to predict what funcs will be needed, and add methods as the necessity appears, if we ever need those methods for a use case, we add them. But if others agree with adding them here, no problem for me. :)
> 
> I agree with you. As this is not a priority, I would like to wait others to state about it before merge or remove the CallerInfo(), CallerPackage(), CallerFile() and CallerLine().
> 
> Thanks for reviewing this.

As there was no feedback, I'm going to remove that helpers.

**Review by josedonizetti — APPROVED** [review]

**Pull request merged**
