### PR TITLE
tracee-ebpf: separate printer and debug package

### PR DESCRIPTION
**Pull request by NDStrahilevitz**
## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description

PR simply separates the logic of the Printer in tracee-ebpf into it's own package. Also separates the debug flag logic to it's own package.
This is done in preparation for the single binary effort.

Fixes: #1266

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [x] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## How Has This Been Tested?

Unit tests were added, modified and checked to run.

- [x] `cmd/tracee-ebpf/internal/printer/printer_test.go§

Reproduce the test by running:

- `make test-unit`

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [x] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented all functions/methods created explaining what they do.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix, or feature, is effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [ ] Use the body to explain what and why instead of how.

### CODE REVIEW

**Comment by NDStrahilevitz** [comment]
Not sure why tests failed, re running on my local machine passed the second time

**Comment by NDStrahilevitz** [comment]
Removed the tests-failed label since they've passed now :)

**Review by yanivagman — COMMENTED** [review]
Nice!

When we will have a logger (#1788), we can probably remove the debug package and just use a debug log level, which will also be available globaly in all tracee packages.

About the printer package, should it really be internal to tracee-ebpf cmd? Maybe we can promote it to be a "regular" package?

**Comment by rafaeldtinoco** [comment]
> When we will have a logger (#1788), we can probably remove the debug package and just use a debug log level, which will also be available globaly in all tracee packages.

Agreed. I thought the same when reviewing that PR.

**Comment by NDStrahilevitz** [comment]
> Nice!
> 
> When we will have a logger (#1788), we can probably remove the debug package and just use a debug log level, which will also be available globaly in all tracee packages.
> 
> About the printer package, should it really be internal to tracee-ebpf cmd? Maybe we can promote it to be a "regular" package?

Yep, agreed about the debug flag, but it is what it is for now.
About the package's location - I kept it there because it is only used in the tracee-ebpf cmd and isn't composed in some other package, so I think it deserves the location. But I don't have much of a strong opinion either way, so if you'd prefer it moves I'll move it.

**Review by yanivagman — APPROVED** [review]
LGTM

**Pull request merged**
