### PR TITLE
Feature/hash so

### PR DESCRIPTION
**Pull request by AlonZivony**
### 1. Explain what the PR does

9fb37130e **feat(events): add hash to symbols_loaded event**
b1e21418e **feat(events): add hash to shared_object_loaded event**

Related to #3576

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
@AlonZivony LGTM, I like it. YOu need to (re)generate the man pages, like the error is telling you to. After that, since all tests passed I can merge right away.

**Comment by rafaeldtinoco** [comment]
image

You need to update the man pages (make man).

**Comment by AlonZivony** [comment]
So it is weird, because I **have** ran `make man`.
You can see that there are .1 pages in the first commit. If I run it again there is no change.

**Comment by geyslan** [comment]
@AlonZivony it's odd. 🤔

I noticed that other .1 files were changed by a lower version of pandoc but the required one.

**Comment by geyslan** [comment]
> @AlonZivony it's odd. 🤔
> 
> I noticed that other .1 files were changed by a lower version of pandoc but the required one.

Well, this made the required changes: https://github.com/aquasecurity/tracee/pull/3720

The comment in pr.yaml was misleading and the docker image was not using a pinned pandoc version; but now it's back on track.

**Comment by rafaeldtinoco** [comment]
> The comment in pr.yaml was misleading and the docker image was not using a pinned pandoc version; but now it's back on track.

With this said, I believe @AlonZivony should rebase, push and then we can merge after tests succeed.

**Comment by rafaeldtinoco** [comment]
Merged by https://github.com/aquasecurity/tracee/pull/3721

**Pull request closed without merging**
