### PR TITLE
docs: replace tracee-ebpf and tracee-rules

### PR DESCRIPTION
**Pull request by josedonizetti**

### CODE REVIEW

**Comment by josedonizetti** [comment]
@itaysk @AnaisUrlichs

**Comment by itaysk** [comment]
@josedonizetti since we wanted to maintain current rules/ebpf docs for the time being, could you include in this PR a copy of the current state inside a directory?

**Comment by AnaisUrlichs** [comment]
@itaysk I have started the restructuring based on Jose's branch & made a copy of the docs before

**Comment by itaysk** [comment]
in this case, should we close this PR?

**Comment by josedonizetti** [comment]
@AnaisUrlichs will open a new one branching from this one.

**Pull request closed without merging**
