### PR TITLE
refactor: move to the new pyroscope package

### PR DESCRIPTION
**Pull request by 06kellyjac**
### 1. Explain what the PR does

Resolves https://github.com/grafana/pyroscope/issues/1941

879c05e73 **refactor: move to the new pyroscope package**

Note:  `make check-pr` assumes `/bin/sh` is `bash` because it uses square brackets

```
Pyroscope has moved to the grafana org
```
	
### 2. Explain how to test it

Build tracee. Run the profiling

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Why does the checklist ask users to label the PR when non-contributors can't label the PR?

**Comment by geyslan** [comment]
> Note: make check-pr assumes /bin/sh is bash because it uses square brackets

Gonna check this. 👍🏼

**Comment by geyslan** [comment]
> Why does the checklist ask users to label the PR when non-contributors can't label the PR?

I approved it to run workflow. Check again if you can set labels. If not, it's not an issue anyway since it's being set automatically.

**Comment by 06kellyjac** [comment]
Yeah, still un-editable for me

image

**Comment by geyslan** [comment]
Thanks for the feedback.

**Review by geyslan — APPROVED** [review]
LGTM.

@06kellyjac thanks.

**Comment by 06kellyjac** [comment]
Thanks for merging 👍

**Pull request merged**
