### PR TITLE
chore: move tracee-rules/main.go to cmd/tracee-rules/main.go

### PR DESCRIPTION
**Pull request by danielpacak**
Signed-off-by: Daniel Pacak <pacak.daniel@gmail.com>

### CODE REVIEW

**Review by rafaeldtinoco — APPROVED** [review]
It all looks good to me. Let me try to do the same thing with tracee-ebpf so we can merge these 2 PRs.

**Review by simar7 — APPROVED** [review]

**Comment by rafaeldtinoco** [comment]
@danielpacak if you don't have any changes, before you rebase & merge, please consider having this merged together in: https://github.com/aquasecurity/tracee/pull/1243/commits (I included this patch in that PR).

**Review by yanivagman — APPROVED** [review]
LGTM!

**Comment by danielpacak** [comment]
We'll merge it with #1243 that cherry-picked this commit.

**Pull request closed without merging**
