### PR TITLE
Fix compilation on ubuntu 16

### PR DESCRIPTION
**Pull request by yanivagman**

### CODE REVIEW

**Comment by yanivagman** [comment]
Tested on ubuntu 16.04

**Review by itaysk — COMMENTED** [review]
I think it would be better to add any libbpf related headers to the `$(LIBBPF_HEADERS)` target, rather then importing directly from 3rdparty source. Also, there's a `make install_uapi_headers` target in libbpf that's may be what you were looking for? if should be called from our `$(LIBBPF_HEADERS)` target

**Comment by yanivagman** [comment]
The problem with their `make install_uapi_headers` is that it install it to the same directory as `make install headers`, which causes the files bpf.h and btf.h to get overriden (and they are not the same files).

From libbpf makefile:
```
PREFIX ?= /usr
LIBDIR ?= $(PREFIX)/$(LIBSUBDIR)
INCLUDEDIR ?= $(PREFIX)/include
UAPIDIR ?= $(PREFIX)/include
```

Any suggestions?

**Comment by yanivagman** [comment]
Nevermind, I think I got it

**Review by itaysk — APPROVED** [review]
approved, is the bpf subdir needed?

**Comment by yanivagman** [comment]
Yes, the bpf subdir is where the libbpf headers are copied to, while the linux subdir is where the linux uapi headers are copied to.
Both are in the LIBBPF_HEADERS dir (dist/libbpf/usr/include)

**Pull request merged**
