### PR TITLE
tracee-ebpf: seperate flag parsing function from main.go

### PR DESCRIPTION
**Pull request by NDStrahilevitz**
This is in preparation for #467.

The pull request simply moves the flag parsing functions for `trace`, `output`, and `capture` in tracee-ebpf to their own files, based on a similar PR by @mtcherni95.

solves #1248.

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
@NDStrahilevitz I believe @yanivagman usually uses the tracee-ebpf flag whenever we do changes to `tracee.bpf.c` (and related) logic. I'll let him to confirm.

**Comment by NDStrahilevitz** [comment]
> @NDStrahilevitz I believe @yanivagman usually uses the tracee-ebpf flag whenever we do changes to `tracee.bpf.c` (and related) logic. I'll let him to confirm.

I'll add him as a reviewer then as well. Which flag specifically did you mean? 
And just noting that this isn't changing any logic, just moves it, is the code in `tracee.bpf.c` dependent on the location of these functions somehow?

**Comment by rafaeldtinoco** [comment]
> I'll add him as a reviewer then as well. Which flag specifically did you mean?

The PR label "tracee-ebpf" (I said flag before, sorry)

**Review by rafaeldtinoco — APPROVED** [review]
LGTM. Makes main look much cleaner.

**Review by yanivagman — COMMENTED** [review]
Thanks @NDStrahilevitz , we definitely need some cleanups in main.
I wonder if we should put these files into a new internal package (https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface).
This can help us in the future with #1288. WDYT?

**Comment by NDStrahilevitz** [comment]
> Thanks @NDStrahilevitz , we definitely need some cleanups in main. I wonder if we should put these files into a new internal package (https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface). This can help us in the future with #1288. WDYT?

I assume you mean as such `/cmd/tracee-ebpf/internal/flags...`? That sounds reasonable to me, i'll add that commit on your confirmation.

**Comment by yanivagman** [comment]
> I assume you mean as such /cmd/tracee-ebpf/internal/flags...? That sounds reasonable to me, i'll add that commit on your confirmation.

Yes, this path is ok. This internal package can be called flags as the path suggests.

**Comment by NDStrahilevitz** [comment]
> Yes, this path is ok. This internal package can be called flags as the path suggests.

Done.

Then I think this is ready to merge, right?

**Pull request merged**
