### PR TITLE
chore(ebpf): not fail if some ksymbol is not found

### PR DESCRIPTION
**Pull request by geyslan**
Close: #3460 

### 1. Explain what the PR does

7b76c016f **chore(ebpf): not fail if some ksymbol is not found**

```
Continue the execution even if some ksymbol is not found or valid.
```

### CODE REVIEW

**Review by yanivagman — APPROVED** [review]
LGTM

**Comment by josedonizetti** [comment]
@geyslan does this cover fully what was the issue https://github.com/aquasecurity/tracee/pull/3476 about? Tracee should have a config for failopen? I'm not sure the config itself is required, though tracee should not fail for any event that can't be loaded in a given kernel, not only ksymbol, but a probe not supporte as well for example?

A quick look and it seems the code doesn't cover it, so it shouldn't close the issue, although you renamed the issue I created, did you create another one for the fail open?

**Comment by geyslan** [comment]
@josedonizetti sorry, I forgot to update you after the offline sync. For now it was only requested to not fail when a ksymbol is not found or is invalid. So I removed the previous `ValidateKsymbolsTable` check, which was just checking for "security_file_open" (and aborting when not found/invalid), and instead let the later called `validateKallsymsDependencies` to log when that happens.

**Comment by geyslan** [comment]
Oh well, news from the front. In our offline sync, it was decided to broad this behaviour to probes etc, leaving the failure reserved only for errors. Opening an issue for this.

**Pull request merged**
