### PR TITLE
Upgrade libbpfgo to v0.4.3-libbpf-1.0.1 and import helpers as own module

### PR DESCRIPTION
**Pull request by grantseltzer**
This upgrades libbpfgo and libbpfgo/helpers to the [latest release](https://github.com/aquasecurity/libbpfgo/releases/tag/v0.4.3-libbpf-1.0.1).

Signed-off-by: grantseltzer <grantseltzer@gmail.com>

## Initial Checklist

- [ ] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [ ] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

commit bb39f4bfa56870c065887decba662599a2386f24 (HEAD -> upgrade-libbpfgo, pfork/upgrade-libbpfgo)
Author: grantseltzer <grantseltzer@gmail.com>
Date:   Mon Oct 10 10:25:45 2022 -0400

    Upgrade libbpfgo to v0.4.3-libbpf-1.0.1 and
    helpers to v0.4.3
    
    Signed-off-by: grantseltzer <grantseltzer@gmail.com>

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [x] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

### CODE REVIEW

**Review by NDStrahilevitz — CHANGES_REQUESTED** [review]
Just tested with this branch, and currently you can't use the helpers in the signatures as it is,
when compiling I get the following errors if I do:
```
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:26:9: could not determine kind of name for C.LIBBPF_MAJOR_VERSION
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:31:9: could not determine kind of name for C.LIBBPF_MINOR_VERSION
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:270:55: could not determine kind of name for C.LIBBPF_STRICT_AUTO_RLIMIT_MEMLOCK
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:271:55: could not determine kind of name for C.LIBBPF_STRICT_MAP_DEFINITIONS
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:269:55: could not determine kind of name for C.LIBBPF_STRICT_NO_OBJECT_LIST
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:268:55: could not determine kind of name for C.LIBBPF_STRICT_SEC_NAME
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:627:9: could not determine kind of name for C.bpf_map__lookup_elem
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:436:15: could not determine kind of name for C.bpf_map_create
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:882:7: could not determine kind of name for C.bpf_object__next_map
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:905:7: could not determine kind of name for C.bpf_object__next_program
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:1189:21: could not determine kind of name for C.bpf_program__type
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:1888:16: could not determine kind of name for C.libbpf_probe_bpf_map_type
../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:1896:16: could not determine kind of name for C.libbpf_probe_bpf_prog_type
cgo: 
clang errors for preamble:
In file included from ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:5:
./libbpfgo.h:75:11: error: no member named 'sz' in 'struct perf_buffer_opts'
  pb_opts.sz = sizeof(struct perf_buffer_opts);
  ~~~~~~~ ^
./libbpfgo.h:77:57: error: too many arguments to function call, expected 3, have 6
  pb = perf_buffer__new(map_fd, page_cnt, perfCallback, perfLostCallback,
       ~~~~~~~~~~~~~~~~                                 ^~~~~~~~~~~~~~~~~
/usr/include/bpf/libbpf.h:682:1: note: 'perf_buffer__new' declared here
perf_buffer__new(int map_fd, size_t page_cnt,
^
2 errors generated.
```

This is important if we want to remove our dependency argument parsing.

**Comment by grantseltzer** [comment]
> Just tested with this branch, and currently you can't use the helpers in the signatures as it is, when compiling I get the following errors if I do:
> 
> ```
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:26:9: could not determine kind of name for C.LIBBPF_MAJOR_VERSION
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:31:9: could not determine kind of name for C.LIBBPF_MINOR_VERSION
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:270:55: could not determine kind of name for C.LIBBPF_STRICT_AUTO_RLIMIT_MEMLOCK
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:271:55: could not determine kind of name for C.LIBBPF_STRICT_MAP_DEFINITIONS
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:269:55: could not determine kind of name for C.LIBBPF_STRICT_NO_OBJECT_LIST
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:268:55: could not determine kind of name for C.LIBBPF_STRICT_SEC_NAME
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:627:9: could not determine kind of name for C.bpf_map__lookup_elem
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:436:15: could not determine kind of name for C.bpf_map_create
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:882:7: could not determine kind of name for C.bpf_object__next_map
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:905:7: could not determine kind of name for C.bpf_object__next_program
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:1189:21: could not determine kind of name for C.bpf_program__type
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:1888:16: could not determine kind of name for C.libbpf_probe_bpf_map_type
> ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:1896:16: could not determine kind of name for C.libbpf_probe_bpf_prog_type
> cgo: 
> clang errors for preamble:
> In file included from ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.2-libbpf-1.0.1/libbpfgo.go:5:
> ./libbpfgo.h:75:11: error: no member named 'sz' in 'struct perf_buffer_opts'
>   pb_opts.sz = sizeof(struct perf_buffer_opts);
>   ~~~~~~~ ^
> ./libbpfgo.h:77:57: error: too many arguments to function call, expected 3, have 6
>   pb = perf_buffer__new(map_fd, page_cnt, perfCallback, perfLostCallback,
>        ~~~~~~~~~~~~~~~~                                 ^~~~~~~~~~~~~~~~~
> /usr/include/bpf/libbpf.h:682:1: note: 'perf_buffer__new' declared here
> perf_buffer__new(int map_fd, size_t page_cnt,
> ^
> 2 errors generated.
> ```
> 
> This is important if we want to remove our dependency argument parsing.

I think your issue is dynamically linking against an out of date locally installed version of libbpf, and not how we're breaking up the go modules. Libbpfgo had to be imported for the helpers package before this change as well. I'm going to work on reproducing your issue right now.

**Comment by NDStrahilevitz** [comment]
> I think your issue is dynamically linking against an out of date locally installed version of libbpf, and not how we're breaking up the go modules. Libbpfgo had to be imported for the helpers package before this change as well. I'm going to work on reproducing your issue right now.

I know, and one of the benefits we can have from separating is that we wouldn't need libbpfgo for the helpers, which is my goal. I don't think signatures should deal with linking against libbpf at all just so it can use the helpers. In fact most standalone signatures would be in repos not necessarily importing libbpfgo at all.

**Comment by rafaeldtinoco** [comment]
> In fact most standalone signatures would be in repos not necessarily importing libbpfgo at all.

Agreed.

**Comment by grantseltzer** [comment]
I've fully separated the two modules now.

**Review by NDStrahilevitz — APPROVED** [review]
LGTM!

Just did my test from before and it compiles and run successfully, and works without `-o option: parse-arguments`.

Infrastructure to write signatures is slightly uncomfortable atm, something like this is needed (@AsafEitani):
image

But that's another issue altogether.

**Pull request merged**
