### PR TITLE
flags: cli: docs: rename trace flag to filter

### PR DESCRIPTION
**Pull request by geyslan**
Fixes: #2751

- #2751

### 1. Explain what the PR does

    flags: cli: docs: rename trace flag to filter
    
    This is a breaking change, but it is necessary to provide a more
    consistent user experience.
    
    The flag is now called --filter, and the docs are updated to reflect
    the new name.

### 2. Explain how to test it

```shell
./dist/tracee --filter help

sudo ./dist/tracee -f container
sudo ./dist/tracee --filter container
sudo ./dist/tracee --filter comm=uname --filter 'pid>0'
...
```

### 3. Other comments

- **Breaking Change**

### CODE REVIEW

**Review by yanivagman — APPROVED** [review]
LGTM

**Comment by geyslan** [comment]
@roikol @AsafEitani this will surely break e2e tests so I'll wait for a signal from your side before merging it.

**Comment by rafaeldtinoco** [comment]
@geyslan https://github.com/aquasecurity/tracee/pull/2776 has merged new testers but, since this already passed the old ones, I think you're good to merge it as you think its appropriate (likely sinking with research like you looked for already).

**Comment by AsafEitani** [comment]
> @roikol @AsafEitani this will surely break e2e tests so I'll wait for a signal from your side before merging it.

@geyslan you can merge, we updated the e2e

**Pull request merged**
