### PR TITLE
feat: add libbpfgo selftests to github actions

### PR DESCRIPTION
**Pull request by grantseltzer**
Signed-off-by: grantseltzer <grantseltzer@gmail.com>

### CODE REVIEW

**Comment by grantseltzer** [comment]
Perhaps premature to be opening this but it's failing because the test is running on an outdated kernel. Since we need to have selftests run on various kernels/distros we should have a test in the selftest run script for this, will add that to this PR.

**Comment by grantseltzer** [comment]
Alright I changed it so that insufficient kernel version doesn't cause a failure.

**Comment by grantseltzer** [comment]
There's a couple of changes in this that are just gofmt changes from a previous PR

**Comment by grantseltzer** [comment]
@itaysk ptal

**Review by itaysk — APPROVED** [review]

**Comment by itaysk** [comment]
LGTM

I'd prefer if I was not always the gatekeeper for merging things. I mean it's always OK to ping a specific maintainer for review, but in most cases I hope maintainers can unblock each other

**Pull request merged**
