### PR TITLE
makefile: add check-pr rule

### PR DESCRIPTION
**Pull request by geyslan**
### 1. Explain what the PR does

90217202 **makefile: add check-pr rule** _<sub>(2023/jun/07) Geyslan Gregório \<geyslan@gmail.com\></sub>_

```
This rule will run all code checks (not tests) and output a formatted
summary of all commits that are not yet in the main branch to be used
for pull requests head comments.
```

### 2. Explain how to test it

From your working branch, after commits created, run `make check-pr`.

### 3. Other comments

Chore.

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
Hum, its best if we change "resume" (meaning returning from interruption) to something that describes "summary". make pr-summary ? Or something simpler, if you prefer.

**Comment by rafaeldtinoco** [comment]
Also, please keep the Author format as "Name <email@domain>" please. Anything git related usually use that as a reference to authors.

Other than that, I like the summary idea, we have to advertise in the github template as well .

**Comment by geyslan** [comment]
> Hum, its best if we change "resume" (meaning returning from interruption) to something that describes "summary". make pr-summary ? Or something simpler, if you prefer.

`make before-push`?

**Comment by geyslan** [comment]
> `make before-push`? `make check-push`?

`check-pr` for the win.

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Comment by rafaeldtinoco** [comment]
ACTUALLY... thinking straight now.. WDYT about removing the ========== ? I know you fixed a 80 cols to the "====" line, but sometimes terminals aren't fully 80 cols, and it brakes terminal output. I'd rather have **** SOMETHING **** or something else, but not a header that obligates to have a specific number of columns in the terminal, WDYT ?

**Comment by rafaeldtinoco** [comment]
Yep, thanks for the change/fix.

**Pull request merged**
