### PR TITLE
[REBASE ONLY] for the PR: #1971

### PR DESCRIPTION
**Pull request by rafaeldtinoco**
This is a rebase for PR: #1971 , squashing 2 commits and solving minor conflicts.

### CODE REVIEW

**Comment by yanivagman** [comment]
To avoid an extra context switch while reading the map value in userspace, wouldn't it have been better to read the map value in sys_exit and send it as part of the event?

Also, shouldn't we change the fd argument type to string now?

**Comment by rafaeldtinoco** [comment]
@yanivagman I'm sorry Yaniv, I thought you were out next couple of weeks or else I would have pinged you before merging it. About the fd argument change, if no signatures are relying in fd being an integer we could. I thought about this feature being "an extra" to introspection (more than anything else) as it adds some extra processing that we don't want when dealing with signatures. WDYT ?

**Comment by geyslan** [comment]
> Also, shouldn't we change the fd argument type to string now?

@yanivagman if `parse-arguments-fds` is set, yeah, userspace outputs json as `fdArg.Value.(String)` even though it is initialized as `fdArg.Value.(int32)`.

**Comment by yanivagman** [comment]
> > Also, shouldn't we change the fd argument type to string now?
> 
> @yanivagman if `parse-arguments-fds` is set, yeah, userspace outputs json as `fdArg.Value.(String)` even though it is initialized as `fdArg.Value.(int32)`.

If this is the output:
`[{"name":"fd","type":"int","value":"3=/etc/passwd"},`
Then type should be string then

**Comment by yanivagman** [comment]
> @yanivagman I'm sorry Yaniv, I thought you were out next couple of weeks or else I would have pinged you before merging it. About the fd argument change, if no signatures are relying in fd being an integer we could. I thought about this feature being "an extra" to introspection (more than anything else) as it adds some extra processing that we don't want when dealing with signatures. WDYT ?

Yes, makes sense

**Comment by rafaeldtinoco** [comment]
@geyslan could you move the event generation to sys_exit() then, based in Yaniv's feedback ? Thanks!

**Pull request merged**
