### PR TITLE
cmd/tracee-ebpf: fix wrong kernel version format

### PR DESCRIPTION
**Pull request by AlonZivony**
## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

Fixed format of the compared kernel version to match expected one.
This way, there won't be wrong parsing of the version string.

Fixes: #2118

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## How Has This Been Tested?

Tests being included in this PR:

- [ ] Test File A
- [ ] Test File B

Reproduce the test by running:

- command 01
- command 02

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [ ] My code follows the style guidelines (C and Go) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [ ] Subject starts with "subsystem|file: description".
- [ ] Do not end the subject line with a period.
- [ ] Limit the subject line to 50 characters.
- [ ] Separate subject from body with a blank line.
- [ ] Use the imperative mood in the subject line.
- [ ] Wrap the body at 72 characters.
- [ ] Use the body to explain what and why instead of how.

### CODE REVIEW

**Review by rafaeldtinoco — CHANGES_REQUESTED** [review]
This should be fixed in libbpfgo IMO. @grantseltzer can we include this fix before the libbpfgo release we're planning ? This way it will be good once we bump tracee.

**Comment by grantseltzer** [comment]
@rafaeldtinoco Where in libbpfgo are you referencing?

**Comment by grantseltzer** [comment]
> This should be fixed in libbpfgo IMO. @grantseltzer can we include this fix before the libbpfgo release we're planning ? This way it will be good once we bump tracee.

Yes I agree, ill write up an issue and add it to the milestone

**Comment by rafaeldtinoco** [comment]
Alright, Im closing this as we agreed it should be fixed in libbpfgo before the next bump. Thanks!

**Pull request closed without merging**
