### PR TITLE
signatures: add event name to golang sigs

### PR DESCRIPTION
**Pull request by josedonizetti**
Fix https://github.com/aquasecurity/tracee/issues/2409

### CODE REVIEW

**Review by yanivagman — COMMENTED** [review]
Some event names are very long, e.g. cgroup_notify_on_release_modification.
This can be inconventient for the user to spefcify such a long event name, and will also cause the table printer to have wrong identations (event name is expected to be up to 15 chars)

**Comment by josedonizetti** [comment]
@yanivagman Agree names too big might be inconvenient. But event names also must be meaningful, and 15 charts might be too short for it. So table output should expect a higher limit for indentation. Maybe 30 charts?

I'll refactor a few of the existing ones.

**Comment by yanivagman** [comment]
> @yanivagman Agree names too big might be inconvenient. But event names also must be meaningful, and 15 charts might be too short for it. So table output should expect a higher limit for indentation. Maybe 30 charts?
> 
> I'll refactor a few of the existing ones.

30 chars may be too wide - see the output of the table printer, this will cause events to be split into two lines.
Anyway, we can also trim the event name from the table printer, I think this is also an option.

**Comment by josedonizetti** [comment]
@yanivagman I don't think we should limit names due to table output which is something used for quick tests only, anyone using tracee seriously in dev/staging/production will be using JSON, or another format, but not a table. Or do you see use cases specifically for table?

**Comment by yanivagman** [comment]
> @yanivagman I don't think we should limit names due to table output which is something used for quick tests only, anyone using tracee seriously in dev/staging/production will be using JSON, or another format, but not a table. Or do you see use cases specifically for table?

This is why I suggested to trim the event name for table output

**Review by yanivagman — APPROVED** [review]
LGTM

**Pull request merged**
