### PR TITLE
events: always detect originated syscall

### PR DESCRIPTION
**Pull request by AlonZivony**
## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

Always evict the originated syscall argument for internal hooks events.
Remove the `detect-syscall` output option that was used to make it available.
Fix documentation to match new format.

Fixes: #2391 

## Type of change

- [ ] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [x] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [x] Breaking change (cause existing functionality not to work as expected).

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [ ] My code follows the style guidelines (C and Go) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [ ] Subject starts with "subsystem|file: description".
- [ ] Do not end the subject line with a period.
- [ ] Limit the subject line to 50 characters.
- [ ] Separate subject from body with a blank line.
- [ ] Use the imperative mood in the subject line.
- [ ] Wrap the body at 72 characters.
- [ ] Use the body to explain what and why instead of how.

### CODE REVIEW

**Comment by AlonZivony** [comment]
@rafaeldtinoco can you check the bug with the linter here?
It has a comment on a specific line which is clearly the same format as all other lines.
Maybe it is an old version with a bug?
In my computer the linter is OK with this line change, and even force me to do it.

**Comment by rafaeldtinoco** [comment]
> @rafaeldtinoco can you check the bug with the linter here?

Did you use go1.18 "gofmt" binary ? There are some discrepancies among different gofmt tools.

**Comment by rafaeldtinoco** [comment]
My golang1.18 gofmt does exactly what the complain was:

image

as you can see here:

image

So I bet you're relying on an older gofmt version OR your IDE's auto-formatting feature... no?

**Review by rafaeldtinoco — APPROVED** [review]
LGTM if it passes the tests (after @AlonZivony fixes the formatting issue). @geyslan please give your +1 before we can merge (due to multi scopes priority).

**Comment by geyslan** [comment]
> 

The same happens here with go 1.19. I'm running fmt-fix inside the vagrant box that has go 1.18.

image

**Comment by AlonZivony** [comment]
> My golang1.18 gofmt does exactly what the complain was:
> 
> image
> 
> as you can see here:
> 
> image
> 
> So I bet you're relying on an older gofmt version OR your IDE's auto-formatting feature... no?

If you will look at all of the other tests in the file, you would see that this is the only lines not indented.
There is no logic in these lines to be not indented like all of the rest.
I think this is a bug with the linter.

**Comment by geyslan** [comment]
> > My golang1.18 gofmt does exactly what the complain was:
> > image
> > as you can see here:
> > image
> 
> If you will look at all of the other tests in the file, you would see that these are the only lines not indented: image There is no logic in these lines to be not indented like all of the rest. I think this is a bug with the linter.
> 
> > So I bet you're relying on an older gofmt version OR your IDE's auto-formatting feature... no?
> 
> Yea, I use goland auto-formatting

Indeed, try this (changing the _pressed tab_ to its _escaped_ `"\t"`); I think this solves it.

image

**Review by yanivagman — APPROVED** [review]
LGTM

**Review by rafaeldtinoco — CHANGES_REQUESTED** [review]
Needs rebase and the formatting fix for it to be merged.

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Pull request merged**
