### PR TITLE
pkg/derive: use up-to-date kernelSymbols

### PR DESCRIPTION
**Pull request by roikol**
use global variable of KernelSymbols in derive package to ensure using the updated kernel symbols at all times

## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

```
Author: RoiKol <roi.kol@aquasec.com>
Date:   Tue Dec 27 13:27:38 2022 +0200

    pkg/derive: use up-to-date kernelSymbols
    
    use global variable of KernelSymbols in derive package to ensure
    using the updated kernel symbols at all times
```

Fixes: #2526

## Type of change

- [x] Bug fix (non-breaking change fixing an issue, preferable).
- [ ] Quick fix (minor non-breaking change requiring no issue, use with care)
- [ ] Code refactor (code improvement and/or code removal)
- [ ] New feature (non-breaking change adding functionality).
- [ ] Breaking change (cause existing functionality not to work as expected).

## How Has This Been Tested?

Tests being included in this PR:

- [ ] Test File A
- [ ] Test File B

Reproduce the test by running:

- command 01
- command 02

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [x] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented all functions/methods created explaining what they do.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix, or feature, is effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Comment by NDStrahilevitz** [comment]
In the next version of libbpfgo we've added a `Refresh` method for the `KernelSymbolsTable`. As such I think a global variable won't be needed since the injected object can be refreshed and updated.
Since we will likely also move to a lazy version of the `KernelSymbolsTable` (see https://github.com/aquasecurity/libbpfgo/pull/282), it's possible you won't have to do refreshes (up to your decision).

**Comment by roikol** [comment]
> In the next version of libbpfgo we've added a `Refresh` method for the `KernelSymbolsTable`. As such I think a global variable won't be needed since the injected object can be refreshed and updated. Since we will likely also move to a lazy version of the `KernelSymbolsTable` (see [aquasecurity/libbpfgo#282](https://github.com/aquasecurity/libbpfgo/pull/282)), it's possible you won't have to do refreshes (up to your decision).

ok, so when we start using the new libbpfgo version, i'll use the `Refresh` method in the derivation func.
thanks @NDStrahilevitz !

**Comment by NDStrahilevitz** [comment]
> ok, so when we start using the new libbpfgo version, i'll use the `Refresh` method in the derivation func. thanks @NDStrahilevitz !

You already have a mechanism for updating the ksymbols, in `tracee.go/updateKallsyms`. You should use `Refresh` there.
What you were trying to fix is probably related to the fact that the dependncy injection of the derivation would keep the old object, but since you will always have the same reference now, doing the `Refresh` somewhere external like the `updateKallsyms` will be better.

**Comment by roikol** [comment]
> the

oh i see, the reference wouldn't change once we'll use the new version, so the problem should not exists anymore

**Pull request closed without merging**
