### PR TITLE
chore(proctree): add process tree e2e tests

### PR DESCRIPTION
**Pull request by AlonZivony**
### 1. Explain what the PR does

Create an end-to-end test for the process tree data source. This in fact test the process tree functionality as a whole.

This PR was divided from #3054

### CODE REVIEW

**Comment by AlonZivony** [comment]
I am not taking ownership on these tests, only wrote them so there will be a method to know that the process tree works well.

**Comment by rafaeldtinoco** [comment]
@AlonZivony are you fixing the PR at least ? =o)

**Comment by rafaeldtinoco** [comment]
Since you won't take ownership of the tests, but we have to, I'm taking over this PR. I will change a big what you did with commits on top of the ones you provided and merge in another PR after making sure tests are good. Thanks for the work on proctree so far Alon! Will try to have this in this next release (v0.18.0)

**Comment by rafaeldtinoco** [comment]
BTW @AlonZivony,

$ sudo ./dist/tracee --signatures-dir=./dist/e2e-inst-signatures --output json --output option:

```
parse-arguments --proctree source=events --events PROCESS_TREE_DATA_SOURCE
{"level":"error","ts":1696428529.9399617,"msg":"Handling event by signature Process Tree Data Source Test: process info existing threads (map[]) doesn't record current thread (1716510)"}
{"level":"error","ts":1696428529.9399986,"msg":"Handling event by signature Process Tree Data Source Test: process info existing threads (map[]) doesn't record current thread (1716509)"}
{"level":"error","ts":1696428529.9400153,"msg":"Handling event by signature Process Tree Data Source Test: process info existing threads (map[]) doesn't record current thread (1716530)"}
{"level":"error","ts":1696428529.940042,"msg":"Handling event by signature Process Tree Data Source Test: process info existing threads (map[]) doesn't record current thread (1716549)"}
{"level":"error","ts":1696428535.8504207,"msg":"Handling event by signature Process Tree Data Source Test: process info existing threads (map[]) doesn't record current thread (1717113)"}
{"level":"error","ts":1696428542.1285655,"msg":"Handling event by signature Process Tree Data Source Test: process info existing threads (map[]) doesn't record current thread (1717684)"}
{"level":"error","ts":1696428542.12991,"msg":"Handling event by signature Process Tree Data Source Test: process info existing threads (map[]) doesn't record current thread (1717666)"}
{"level":"error","ts":1696428542.1299436,"msg":"Handling event by signature Process Tree Data Source Test: process info existing threads (map[]) doesn't record current thread (1717696)"}
{"level":"error","ts":1696428542.1316833,"msg":"Handling event by signature Process Tree Data Source Test: process info existing threads (map[]) doesn't record current thread (1717734)"}
```

I changed the thread creation test to something bigger and I started getting PID 0, or binary path "", or inexistent entries.

```
$ TIMES=4 ./proctreetester

$ pstree -t -p $(ps -ef | grep proctreetester | awk '{print $2}' | sort | head -1 ) 
tester-4(1685587)─┬─spawning(1685588)─┬─{another}(1685592)
                  │                   ├─{sleeping}(1685591)
                  │                   └─{sleeping}(1685595)
                  ├─tester-3(1685589)─┬─spawning(1685597)─┬─{another}(1685625)
                  │                   │                   ├─{sleeping}(1685624)
                  │                   │                   └─{sleeping}(1685643)
                  │                   ├─tester-2(1685599)─┬─spawning(1685614)─┬─{another}(1685731)
                  │                   │                   │                   ├─{sleeping}(1685729)
                  │                   │                   │                   └─{sleeping}(1685733)
                  │                   │                   ├─tester-1(1685618)─┬─no-more-tests(1685773)
                  │                   │                   │                   └─spawning(1685771)─┬─{another}(1685778)
                  │                   │                   │                                       ├─{sleeping}(1685777)
                  │                   │                   │                                       └─{sleeping}(1685811)
                  │                   │                   └─tester-1(1685621)─┬─no-more-tests(1685642)
                  │                   │                                       └─spawning(1685640)─┬─{another}(1685774)
                  │                   │                                                           ├─{sleeping}(1685772)
                  │                   │                                                           └─{sleeping}(1685779)
                  │                   ├─tester-2(1685602)─┬─spawning(1685649)─┬─{another}(1685700)
                  │                   │                   │                   ├─{sleeping}(1685699)
                  │                   │                   │                   └─{sleeping}(1685735)
                  │                   │                   ├─tester-1(1685650)─┬─no-more-tests(1685680)
                  │                   │                   │                   └─spawning(1685679)─┬─{another}(1685686)
                  │                   │                   │                                       ├─{sleeping}(1685685)
                  │                   │                   │                                       └─{sleeping}(1685705)
                  │                   │                   └─tester-1(1685651)─┬─no-more-tests(1685665)
                  │                   │                                       └─spawning(1685663)─┬─{another}(1685704)
                  │                   │                                                           ├─{sleeping}(1685703)
                  │                   │                                                           └─{sleeping}(1685709)
                  │                   └─tester-2(1685605)─┬─spawning(1685632)─┬─{another}(1685710)
                  │                                       │                   ├─{sleeping}(1685708)
                  │                                       │                   └─{sleeping}(1685780)
                  │                                       ├─tester-1(1685636)─┬─no-more-tests(1685783)
                  │                                       │                   └─spawning(1685781)─┬─{another}(1685787)
                  │                                       │                                       ├─{sleeping}(1685785)
                  │                                       │                                       └─{sleeping}(1685812)
                  │                                       └─tester-1(1685638)─┬─no-more-tests(1685732)
                  │                                                           └─spawning(1685727)─┬─{another}(1685752)
                  │                                                                               ├─{sleeping}(1685751)
                  │                                                                               └─{sleeping}(1685754)
                  ├─tester-3(1685590)─┬─spawning(1685596)─┬─{another}(1685609)
                  │                   │                   ├─{sleeping}(1685607)
                  │                   │                   └─{sleeping}(1685711)
                  │                   ├─tester-2(1685598)─┬─spawning(1685635)─┬─{another}(1685770)
                  │                   │                   │                   ├─{sleeping}(1685769)
                  │                   │                   │                   └─{sleeping}(1685809)
                  │                   │                   ├─tester-1(1685637)─┬─no-more-tests(1685786)
                  │                   │                   │                   └─spawning(1685784)─┬─{another}(1685790)
                  │                   │                   │                                       ├─{sleeping}(1685789)
                  │                   │                   │                                       └─{sleeping}(1685813)
                  │                   │                   └─tester-1(1685639)─┬─no-more-tests(1685707)
                  │                   │                                       └─spawning(1685706)─┬─{another}(1685776)
                  │                   │                                                           ├─{sleeping}(1685775)
                  │                   │                                                           └─{sleeping}(1685810)
                  │                   ├─tester-2(1685600)─┬─spawning(1685617)─┬─{another}(1685764)
                  │                   │                   │                   ├─{sleeping}(1685762)
                  │                   │                   │                   └─{sleeping}(1685767)
                  │                   │                   ├─tester-1(1685622)─┬─no-more-tests(1685671)
                  │                   │                   │                   └─spawning(1685669)─┬─{another}(1685678)
                  │                   │                   │                                       ├─{sleeping}(1685674)
                  │                   │                   │                                       └─{sleeping}(1685714)
                  │                   │                   └─tester-1(1685626)─┬─no-more-tests(1685672)
                  │                   │                                       └─spawning(1685670)─┬─{another}(1685713)
                  │                   │                                                           ├─{sleeping}(1685712)
                  │                   │                                                           └─{sleeping}(1685782)
                  │                   └─tester-2(1685603)─┬─spawning(1685615)─┬─{another}(1685698)
                  │                                       │                   ├─{sleeping}(1685697)
                  │                                       │                   └─{sleeping}(1685734)
                  │                                       ├─tester-1(1685619)─┬─no-more-tests(1685791)
                  │                                       │                   └─spawning(1685788)─┬─{another}(1685795)
                  │                                       │                                       ├─{sleeping}(1685794)
                  │                                       │                                       └─{sleeping}(1685814)
                  │                                       └─tester-1(1685623)─┬─no-more-tests(1685702)
                  │                                                           └─spawning(1685701)─┬─{another}(1685739)
                  │                                                                               ├─{sleeping}(1685738)
                  │                                                                               └─{sleeping}(1685760)
                  ├─tester-3(1685593)─┬─spawning(1685610)─┬─{another}(1685647)
                  │                   │                   ├─{sleeping}(1685646)
                  │                   │                   └─{sleeping}(1685648)
                  │                   ├─tester-2(1685611)─┬─spawning(1685658)─┬─{another}(1685730)
                  │                   │                   │                   ├─{sleeping}(1685728)
                  │                   │                   │                   └─{sleeping}(1685745)
                  │                   │                   ├─tester-1(1685659)─┬─no-more-tests(1685744)
                  │                   │                   │                   └─spawning(1685743)─┬─{another}(1685748)
                  │                   │                   │                                       ├─{sleeping}(1685746)
                  │                   │                   │                                       └─{sleeping}(1685805)
                  │                   │                   └─tester-1(1685660)─┬─no-more-tests(1685750)
                  │                   │                                       └─spawning(1685749)─┬─{another}(1685755)
                  │                   │                                                           ├─{sleeping}(1685753)
                  │                   │                                                           └─{sleeping}(1685756)
                  │                   ├─tester-2(1685612)─┬─spawning(1685718)─┬─{another}(1685726)
                  │                   │                   │                   ├─{sleeping}(1685725)
                  │                   │                   │                   └─{sleeping}(1685803)
                  │                   │                   ├─tester-1(1685721)─┬─no-more-tests(1685793)
                  │                   │                   │                   └─spawning(1685792)─┬─{another}(1685797)
                  │                   │                   │                                       ├─{sleeping}(1685796)
                  │                   │                   │                                       └─{sleeping}(1685798)
                  │                   │                   └─tester-1(1685724)─┬─no-more-tests(1685741)
                  │                   │                                       └─spawning(1685740)─┬─{another}(1685759)
                  │                   │                                                           ├─{sleeping}(1685758)
                  │                   │                                                           └─{sleeping}(1685768)
                  │                   └─tester-2(1685613)─┬─spawning(1685629)─┬─{another}(1685684)
                  │                                       │                   ├─{sleeping}(1685682)
                  │                                       │                   └─{sleeping}(1685687)
                  │                                       ├─tester-1(1685631)─┬─no-more-tests(1685676)
                  │                                       │                   └─spawning(1685673)─┬─{another}(1685683)
                  │                                       │                                       ├─{sleeping}(1685681)
                  │                                       │                                       └─{sleeping}(1685696)
                  │                                       └─tester-1(1685634)─┬─no-more-tests(1685666)
                  │                                                           └─spawning(1685664)─┬─{another}(1685691)
                  │                                                                               ├─{sleeping}(1685690)
                  │                                                                               └─{sleeping}(1685695)
                  └─tester-3(1685594)─┬─spawning(1685601)─┬─{another}(1685620)
                                      │                   ├─{sleeping}(1685616)
                                      │                   └─{sleeping}(1685627)
                                      ├─tester-2(1685604)─┬─spawning(1685628)─┬─{another}(1685763)
                                      │                   │                   ├─{sleeping}(1685761)
                                      │                   │                   └─{sleeping}(1685804)
                                      │                   ├─tester-1(1685630)─┬─no-more-tests(1685653)
                                      │                   │                   └─spawning(1685652)─┬─{another}(1685689)
                                      │                   │                                       ├─{sleeping}(1685688)
                                      │                   │                                       └─{sleeping}(1685694)
                                      │                   └─tester-1(1685633)─┬─no-more-tests(1685668)
                                      │                                       └─spawning(1685667)─┬─{another}(1685737)
                                      │                                                           ├─{sleeping}(1685736)
                                      │                                                           └─{sleeping}(1685747)
                                      ├─tester-2(1685606)─┬─spawning(1685641)─┬─{another}(1685662)
                                      │                   │                   ├─{sleeping}(1685661)
                                      │                   │                   └─{sleeping}(1685692)
                                      │                   ├─tester-1(1685644)─┬─no-more-tests(1685655)
                                      │                   │                   └─spawning(1685654)─┬─{another}(1685677)
                                      │                   │                                       ├─{sleeping}(1685675)
                                      │                   │                                       └─{sleeping}(1685693)
                                      │                   └─tester-1(1685645)─┬─no-more-tests(1685657)
                                      │                                       └─spawning(1685656)─┬─{another}(1685722)
                                      │                                                           ├─{sleeping}(1685719)
                                      │                                                           └─{sleeping}(1685742)
                                      └─tester-2(1685608)─┬─spawning(1685715)─┬─{another}(1685723)
                                                          │                   ├─{sleeping}(1685720)
                                                          │                   └─{sleeping}(1685757)
                                                          ├─tester-1(1685716)─┬─no-more-tests(1685800)
                                                          │                   └─spawning(1685799)─┬─{another}(1685802)
                                                          │                                       ├─{sleeping}(1685801)
                                                          │                                       └─{sleeping}(1685815)
                                                          └─tester-1(1685717)─┬─no-more-tests(1685766)
                                                                              └─spawning(1685765)─┬─{another}(1685807)
                                                                                                  ├─{sleeping}(1685806)
                                                                                                  └─{sleeping}(1685808)
```

And you can see that the signature being processed at "SchedExec" can't cope with the proctree data source just because both are being fed by the same event(s) (sched_process_exec).

Mathematically speaking, if the ratio of process/thread creation is just a bit bigger (2 process, 6 threads), which is incredibly small if we think of the entire OS, then the signature data source logic may lag/jitter behind. The signature logic is much simpler than the datasource entry handling, so the process tree processing gets a bit queued and the queries start to fail. This can be seen if I execute my new test with:

$ TIMES=4 ./proctreetester

and then

$ TIMES=2 ./proctreetester

and

$ TIMES=1 ./proctreetester

The process hierarchy it creates grows and shrinks exponentially, so you will see more or less errors from the signature.

This is **very important** if you are willing to use the process tree from the signatures. I'm not sure this issue exists when processing other types of events (other then exec), but I would think so.

**Comment by AlonZivony** [comment]
If I am not wrong, when using the source of events there is no issue, as the processing of the event is blocking before passing it forward.
I agree with you that currently the signals alone are not usable.

**Comment by rafaeldtinoco** [comment]
I tested events, signals, both. Same results.

**Pull request closed without merging**
