### PR TITLE
k8s: fix tracee version to latest release v0.8.1

### PR DESCRIPTION
**Pull request by josedonizetti**
Signed-off-by: Jose Donizetti <jdbjunior@gmail.com>

## Initial Checklist

- [x] There is an issue describing the need for this PR.
- [ ] Git log contains summary of the change.
- [ ] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

Copy and paste the git log here.

Fixes: #2097 

## Type of change

chore: updating tracee on helm/k8s 

## How Has This Been Tested?

```
helm install tracee ./deploy/helm/tracee     --namespace tracee-system --create-namespace     --set hostPID=true
```

## Final Checklist:

Pick "Bug Fix" or "Feature", delete the other and mark appropriate checks.

- [ ] I have made corresponding changes to the documentation.
- [ ] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented all functions/methods created explaining what they do.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Review by rafaeldtinoco — COMMENTED** [review]
Lets hold this and make it 0.8.2 (next week ?). I'm putting it into the milestone.

**Comment by josedonizetti** [comment]
Why? If there is a release now, the deployment should be up to date with it, no? Even if there is another one coming.

**Comment by rafaeldtinoco** [comment]
> Why? If there is a release now, the deployment should be up to date with it, no? Even if there is another one coming.

Fair enough.

**Review by rafaeldtinoco — APPROVED** [review]

**Comment by josedonizetti** [comment]
@rafaeldtinoco i’ll create a specific issue to track the upgrade for the next release

**Pull request merged**
