### PR TITLE
Add Power Support to aquasec tracee

### PR DESCRIPTION
**Pull request by DanielCasali**
Added support to IBM Power for tracee. Values for syscalls from https://github.com/torvalds/linux/blob/master/arch/powerpc/kernel/syscalls/syscall.tbl

### CODE REVIEW

**Comment by yanivagman** [comment]
@DanielCasali adding support for new architectures is welcome.
Other than adding the relevant constants, notice that there are also some places in tracee.bpf.c that are architecture specific.
These can be found by looking for bpf_target_arm64 or bpf_target_x86 (arm64 and x86 architectures, respectively).

Also, when adding support for a new architecture, we have to be sure that it was tested on a relevant platform - did you test your change on such a platform?

**Comment by DanielCasali** [comment]
Hello,
I built the container on Power and I ran the container.
I will look at the bpf_target to check out what I missed.
Thank you!
Daniel

**Review by DanielCasali — COMMENTED** [review]
I just added the changes suggested by @yanivagman to include powerpc into tracee-ebpf/tracee/tracee.bpf.c just like arm64. I got the flag to check for compat on https://github.com/torvalds/linux/blob/master/arch/powerpc/include/asm/thread_info.h

**Comment by DanielCasali** [comment]
Converting to Draft to fix runtime issue... Thank you @yanivagman for the heads up I will work more on it.

**Comment by DanielCasali** [comment]
I did some porting , I can build a container image and run it. the clang is passing without errors - although I still need to fix is_powerpc_compat(struct task_struct *task).

I need help  with "Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map."
I don't think I created any new variables so I don't know where this is coming from. any hints @yanivagman ?
```

/tracee # /usr/bin/clang -S -D__BPF_TRACING__ -D__KERNEL__ -D__TARGET_ARCH_ppc64le -I/tmp/tracee-make779307987 -include/lib/modules/4.18.0-147.el8.ppc64le/source/include/linux/kconfig.h -I/lib/modules/4.18.0-147.el8.ppc64le/source/arch/ppc64le/include -I/lib/modules/4.18.0-147.el8.ppc64le/source/arch/ppc64le/include/uapi -I/lib/modules/4.18.0-147.el8.ppc64le/build/arch/ppc64le/include/generated -I/lib/modules/4.18.0-147.el8.ppc64le/build/arch/ppc64le/include/generated/uapi -I/lib/modules/4.18.0-147.el8.ppc64le/source/include -I/lib/modules/4.18.0-147.el8.ppc64le/build/include -I/lib/modules/4.18.0-147.el8.ppc64le/source/include/uapi -I/lib/modules/4.18.0-147.el8.ppc64le/build/include/generated -I/lib/modules/4.18.0-147.el8.ppc64le/build/include/generated/uapi -Wno-address-of-packed-member -Wno-compare-distinct-pointer-types -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pointer-sign -Wno-pragma-once-outside-heade -Wno-unknown-warning-option -Wno-unused-value -Wunused -Wall -fno-stack-protector -fno-jump-tables -fno-unwind-tables -fno-asynchronous-unwind-tables -xc -nostdinc -O2 -emit-llvm -c -g /tmp/tracee-make779307987/tracee.bpf.c -o/tmp/tracee-make779307987/tracee.bpf.ll
/tracee # /usr/bin/llc -march=bpf -filetype=obj -o /tmp/tracee-make779307987/tracee.bpf.o /tmp/tracee-make779307987/tracee.bpf.ll
error: /tmp/tracee-make779307987/tracee.bpf.c:987:15: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:987:15: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:540:38: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:573:39: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:987:15: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:2002:26: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:0:0: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:597:34: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:540:38: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:573:39: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:0:0: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:0:0: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:1097:9: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:0:0: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
error: /tmp/tracee-make779307987/tracee.bpf.c:2002:26: in function tracepoint__raw_syscalls__sys_enter i32 (%struct.bpf_raw_tracepoint_args*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
```

**Comment by yanivagman** [comment]
@DanielCasali not really.
I guess that this is an architecture specific thing as this code works for x86/arm64.
Sorry, but I'm not familiar at all with powerpc.

**Comment by yanivagman** [comment]
Unless you changed something with the logic of the code? In that case, sharing the diff might help

**Comment by DanielCasali** [comment]
It might be something about the CO-RE that might be enabled (as you can see I am not the expert, just trying to help on my free time). Since it is quick I got here the Diff. Even with the diff it still compiles on x86, I get that only powerpc, so I will dig more about it.

```
78a79,80
> #elif defined(bpf_target_powerpc)
> #define PT_REGS_PARM6(ctx)  ((ctx)->gpr[8])
164a167,181
> #elif defined(bpf_target_powerpc)
> #define SYS_OPEN              5
> #define SYS_MMAP              90
> #define SYS_MPROTECT          125
> #define SYS_RT_SIGRETURN      172
> #define SYS_EXECVE            11
> #define SYS_EXIT              1
> #define SYS_EXIT_GROUP        234
> #define SYS_OPENAT            286
> #define SYS_EXECVEAT          362
> #define SYSCALL_CONNECT       328
> #define SYSCALL_ACCEPT        330
> #define SYSCALL_ACCEPT4       344
> #define SYSCALL_LISTEN        329
> #define SYSCALL_BIND          327
693a711,720
> static __always_inline bool is_powerpc_compat(struct task_struct *task)
> {
> #if defined(bpf_target_powerpc)
>     return READ_KERN(task->thread_info.flags) & _TIF_32BIT;
> #else
>     return false;
> #endif
> }
>
>
699a727,728
> #elif defined(bpf_target_powerpc)
>     return is_powerpc_compat(task);
```

**Comment by yanivagman** [comment]
Did you try to compile with the makefile and not directly? You can compile an object without using core/btf. This also reminds me that there are some things that are architecture specific in the makefile itself, you might want to take a look at that as well

**Comment by rafaeldtinoco** [comment]
This needs rebasing and likely some re-work. We plan to get back to this soon, but I'm closing this for now, and maybe we should open a new PR when the time comes.

**Pull request closed without merging**
