### PR TITLE
tracee-ebpf: add tail calls to event dependencies

### PR DESCRIPTION
**Pull request by yanivagman**
## Initial Checklist

- [ ] There is an issue describing the need for this PR.
- [x] Git log contains summary of the change.
- [x] Git log contains motivation and context of the change.
- [ ] If part of an EPIC, PR git log contains EPIC number.
- [ ] If part of an EPIC, PR was added to EPIC description.

## Description (git log)

Build a generic mechanism to declare the required tail-call for the proper functionality of an event.
In addition, Introudce capture events to take care of capture dependencies (probes and tail-calls) automatically.

## Type of change

New feature (non-breaking change adding functionality).

## How Has This Been Tested?

Manually run and verified the proper functionality of the following events:
- exexcve
- execveat
- socket_dup

Manually run and verified the proper functionality of the following capture features:
- capture write
- capture mem

Tests being included in this PR:

Reproduce the test by running:

## Final Checklist:

- [ ] I have made corresponding changes to the documentation.
- [x] My code follows the style guidelines (C and Go) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented all functions/methods created explaining what they do.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix, or feature, is effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published before.

## Git Log Checklist:

My commits logs have:

- [x] Subject starts with "subsystem|file: description".
- [x] Do not end the subject line with a period.
- [x] Limit the subject line to 50 characters.
- [x] Separate subject from body with a blank line.
- [x] Use the imperative mood in the subject line.
- [x] Wrap the body at 72 characters.
- [x] Use the body to explain what and why instead of how.

### CODE REVIEW

**Review by rafaeldtinoco — CHANGES_REQUESTED** [review]
This is a very nice change. I have proposed a small change on top of it so it is easier for us to understand tail calls types, event dependencies and which tail call types would be enabled per configuration option. WDYT ?

https://github.com/yanivagman/tracee/pull/1

**Comment by yanivagman** [comment]
> This is a very nice change. I have proposed a small change on top of it so it is easier for us to understand tail calls types, event dependencies and which tail call types would be enabled per configuration option. WDYT ?
> 
> [yanivagman#1](https://github.com/yanivagman/tracee/pull/1)

Capture stuff shouldn't be a dependency of an event. For a matter of fact, in a future PR I want to decouple events and capture artifacts, meaning that when some artifact needs to be captured, it has its own dependencies of tail calls (like in this PR) and bpf programs (probes), so no event dependencies should exist then

**Comment by rafaeldtinoco** [comment]
> Capture stuff shouldn't be a dependency of an event. For a matter of fact, in a future PR I want to decouple events and capture artifacts, meaning that when some artifact needs to be captured, it has its own dependencies of tail calls (like in this PR) and bpf programs (probes), so no event dependencies should exist then

Well I liked your change exactly because it associated events with tail calls BUT I don't like having tail calls disclosed somewhere else because I think it is hard to associate which probes depend on which tail call (without having to go through tracee.bpf.c file and finding them out one by one). It will be even harder when we start splitting that file.

I think you should associate all tail calls with the **probes** that depend on them, in the same place, just like you've done with event dependencies. It looks to me that a tailcall is both: a probe AND a capture-option dependency (and not an event dependency only, which I agree).

I can understand some tail calls won't be used if capturing wasn't selected (multiple types of capturing). Then it is the case of not registering them, like I proposed, based on the types of captures.

Feel free to merge mine and make change, change yours, etc. If you still want to use yours, feel free to ask for another review for the conflict resolution.

Thanks

**Comment by yanivagman** [comment]
> Well I liked your change exactly because it associated events with tail calls BUT I don't like having tail calls disclosed somewhere else because I think it is hard to associate which probes depend on which tail call (without having to go through tracee.bpf.c file and finding them out one by one). It will be even harder when we start splitting that file.

I agree with that, and this was my intention in creating this PR. There are two steps for this to happen - associating tail calls with events (done in this PR), and associating tail calls with the different capture feature.
I didn't implement the second step in this PR, as it will require introducing capture definition like we have for events definition, and I think it should be done in a different PR.

So the question is - do you think that this PR takes a step closer to achieving this goal, or is there anything here that I CHANGED that takes us a step back?

**Comment by yanivagman** [comment]
Also note that I wrote that capture stuff shouldn't be a dependency of an event. I didn't say that tail calls shouldn't be a dependency of the capture stuff. Like you said:

> It looks to me that a tailcall is both: a probe AND a capture-option dependency (and not an event dependency only, which I agree).

**Comment by yanivagman** [comment]
Ok @rafaeldtinoco, I combined the two PRs into one for completeness as you suggested.
This should answer your second concern:

> I don't like having tail calls disclosed somewhere else because
> I think it is hard to associate which probes depend on which tail call
> (without having to go through tracee.bpf.c file and finding them out one
> by one). It will be even harder when we start splitting that file.

An event is now self contained (from tail-calls dependencies perspective), and using the event dependencies infrastructure for the capture features avoid code duplication, and makes things more elegant.

**Comment by rafaeldtinoco** [comment]
> An event is now self contained (from tail-calls dependencies perspective), and using the event dependencies infrastructure for the capture features avoids code duplication, and makes things more elegant.

Thanks a lot. I'm reviewing it now.

**Review by rafaeldtinoco — APPROVED** [review]
> Ok @rafaeldtinoco, I combined the two PRs into one for completeness as you suggested. This should answer your second concern:
> 
> > I don't like having tail calls disclosed somewhere else because
> > I think it is hard to associate which probes depend on which tail call
> > (without having to go through tracee.bpf.c file and finding them out one
> > by one). It will be even harder when we start splitting that file.
> 
> An event is now self contained (from tail-calls dependencies perspective), and using the event dependencies infrastructure for the capture features avoids code duplication, and makes things more elegant.

Okay.. definitely the Capture events are not "events" (like all other events purpose) but, tbh, I found the solution elegant. Approving it and thanks for addressing my concern.

**Pull request merged**
