### PR TITLE
fix(tests): fix goroutines leakage in integration tests

### LINKED ISSUE #4044: Flaky integration tests because of unexpected goroutines
## Description

We seem to get a lot of `found unexpected goroutines` errors in the integration tests lately.
For example:
```
=== NAME  Test_EventsDependencies
    dependencies_test.go:158: found unexpected goroutines:
        [Goroutine 13 in state chan send, 1 minutes, with github.com/aquasecurity/tracee/tests/testutils.ExecCmdBgWithSudoAndCtx.func1.1 on top of the stack:
        github.com/aquasecurity/tracee/tests/testutils.ExecCmdBgWithSudoAndCtx.func1.1()
        	/home/runner/work/tracee/tracee/tests/testutils/exec.go:141 +0xcd
        created by github.com/aquasecurity/tracee/tests/testutils.ExecCmdBgWithSudoAndCtx.func1 in goroutine 12
        	/home/runner/work/tracee/tracee/tests/testutils/exec.go:136 +0x2c6
         Goroutine 127 in state chan send, 1 minutes, with github.com/aquasecurity/tracee/tests/testutils.ExecCmdBgWithSudoAndCtx.func1.1 on top of the stack:
        github.com/aquasecurity/tracee/tests/testutils.ExecCmdBgWithSudoAndCtx.func1.1()
        	/home/runner/work/tracee/tracee/tests/testutils/exec.go:141 +0xcd
        created by github.com/aquasecurity/tracee/tests/testutils.ExecCmdBgWithSudoAndCtx.func1 in goroutine 126
        	/home/runner/work/tracee/tracee/tests/testutils/exec.go:136 +0x2c6
         Goroutine 243 in state chan send, with github.com/aquasecurity/tracee/tests/testutils.ExecCmdBgWithSudoAndCtx.func1.1 on top of the stack:
        github.com/aquasecurity/tracee/tests/testutils.ExecCmdBgWithSudoAndCtx.func1.1()
        	/home/runner/work/tracee/tracee/tests/testutils/exec.go:141 +0xcd
        created by github.com/aquasecurity/tracee/tests/testutils.ExecCmdBgWithSudoAndCtx.func1 in goroutine 242
        	/home/runner/work/tracee/tracee/tests/testutils/exec.go:136 +0x2c6
        ]
```
It sabotages the efforts to merge PRs, so we should find its source.

### PR DESCRIPTION
**Pull request by AlonZivony**
### 1. Explain what the PR does

Fix tests so they will make sure to close channels properly and clean goroutines.

Fix #4044

### CODE REVIEW

**Review by NDStrahilevitz — APPROVED** [review]
LGTM, nice job

**Comment by AlonZivony** [comment]
I will soon push some small change so don't merge yet

**Comment by AlonZivony** [comment]
I think we will also need to backport it to 0.21.0 so it won't cause problems there.
Do you agree with me?

**Comment by AlonZivony** [comment]
@NDStrahilevitz can I merge the PR?
I ask because I pushed a minor change and I am not sure if you went over it

**Review by yanivagman — APPROVED** [review]
LGTM

**Pull request merged**
