### PR TITLE
chore(build): change check-pr output format

### PR DESCRIPTION
**Pull request by geyslan**
### 1. Explain what the PR does

4ef7356d6 **chore(build): change check-pr output format**

### CODE REVIEW

**Comment by geyslan** [comment]
For a body-less single commit.

image

**Comment by geyslan** [comment]
I'm not liking how its outputting for body-less commits. I'll try other approach soon.

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Comment by geyslan** [comment]
Now, if the commit doesn't have body it's outputted again in the full list.

I think it is better:

image

**Pull request merged**
